### ISSUE TITLE
Replace fs sync functions with asynchronous versions

### ISSUE THREAD

**Issue by fireantik** [butterproject/butter-desktop#113]
Fs io is very slow, it could easily lead to laggy Butter on several occasions for many people.
Replace fs sync functions with their asynchronous variants.

Just to outline worst offenders:

+ https://github.com/butterproject/butter-desktop/blob/master/src/app/app.js#L184 deleteFolder function - recursive synchronous file deleter. It should use https://www.npmjs.com/package/rimraf
+ https://github.com/butterproject/butter-desktop/blob/master/src/app/templates/settings-container.tpl#L177 recursive function - synchronous recursive directory explorer in a template file.
+ https://github.com/butterproject/butter-desktop/blob/master/src/app/lib/views/file_selector.js#L125 storeTorrent function - sync exist, unlink and write.

**Comment by xaiki** [comment]
patches are welcome =)

**Comment by fireantik** [comment]
I was hoping some of you more experienced guys could make these changes, I fear I don't understand the project well enough to make them work properly, unfortunately...

**Comment by xaiki** [comment]
no problem, adding to the backlog stack =)
