### ISSUE TITLE
Running "exec:linux64" (exec) task failed

### ISSUE THREAD

**Issue by nhducit** [butterproject/butter-desktop#115]
I got this error when execute 'grunt start'

ubuntu: 14.04
npm: 2.14.7
node: 4.2.1

duc@duc:/media/duc/007CA4B433099A90/Projects/butter-desktop$ grunt start
Running "start" task

Running "exec:linux64" (exec) task
>> Exited with code: 126.
>> /bin/sh: 1: build/Butter/linux64/Butter: Permission denied
Warning: Task "exec:linux64" failed. Use --force to continue.

Aborted due to warnings.

**Comment by Valcorb** [comment]
> /bin/sh: 1: build/Butter/linux64/Butter: Permission denied

Try running it with sudo (or as root).

**Comment by xaiki** [comment]
you may have run it as root, try removing everything and cloning all as user.

**Comment by nhducit** [comment]
this is output when running "sudo grunt start"

```
sudo grunt start
[sudo] password for duc: 
Running "start" task

Running "exec:linux64" (exec) task
>> /bin/sh: 1: build/Butter/linux64/Butter: Permission denied
>> Exited with code: 126.
Warning: Task "exec:linux64" failed. Use --force to continue.

Aborted due to warnings.

```

**Comment by szymanskip** [comment]
I believe the problem is with shell:setexectuable task.
I'll try to make PR to fix that.
