### ISSUE TITLE
Community (Blog/Forum) links not working

### ISSUE THREAD

**Issue by colindevs** [butterproject/butter-desktop#123]
**In README, the blog and forum links aren't working:**
![screen shot 2015-10-28 at 8 07 16 pm](https://cloud.githubusercontent.com/assets/12850952/10806913/7407150a-7db0-11e5-81c7-56698e42fb2d.png)
![screen shot 2015-10-28 at 8 07 52 pm](https://cloud.githubusercontent.com/assets/12850952/10806912/73faf9f0-7db0-11e5-8dbe-2a3814132f5c.png)

**The links look pretty legit, so its not a misspell:**

![screen shot 2015-10-28 at 8 18 00 pm](https://cloud.githubusercontent.com/assets/12850952/10806981/2c44476e-7db1-11e5-9b14-76422d6ff4ef.png)

 *I guess the sites just got taken down!*

**Comment by MrAdder** [comment]
Issue is now fixed

**Comment by colindevs** [comment]
Glad to help!
