### ISSUE TITLE
Dropping a video inside butter

### ISSUE THREAD

**Issue by giacomocerquone** [butterproject/butter-desktop#126]
Related to #110 
I fetched and merged the changes on the master branch and now the problem is slightly different.
When I drop a video inside butter the loading circle shows up and disappear while nothing happens.

**Comment by douglascamata** [comment]
@giacomocerquone why would you try to use Butter as a video player for videos you already downloaded? I mean, of course it would be very easy to do that, but what about using real players for this (VLC, MPlayerX, etc)?

**Comment by giacomocerquone** [comment]
I think you're completely missing the point here.
Github is not a forum, is an issue tracker (or bug trucker). I'm a developer, I submit issues to let others solve them or let the others know that I'm solving them. If an application (Butter in this case) doesn't work properly, I warn the developers, included me, so that we can fix it together.
If you think that the possibility that users have to open external movies with Butter is useless, you should open an Issue.

**Comment by douglascamata** [comment]
@giacomocerquone people also communicate in issue trackers and it is good to keep all the discussion that fits in one issue's subject inside it. It is also very good to keep the manners, this is a community, not your private space. You need to chill, bro.

**Comment by giacomocerquone** [comment]
@douglascamata I don't think I said or implied that this is my private space, I specifically said that here we work together. I think I expressed myself in a good and respectful manner, I didn't offend you but if you felt so I can understand that and I ask you sorry. Please don't take those words as an offense.
I wasn't nervous so no need to chill :)

Anyway you do know why butter behave like this?

**Comment by douglascamata** [comment]
Ok. Don't know why, but I think it's a player issue. Need to check what we send to the player when a video is dropped on Butter, although I'm working now and  can't take a look at this. Maybe at lunch, if I have time, or later at home.

**Comment by nordjac** [comment]
You could drop a video in PT to automatically fetch subtitles and if you had trakt.tv it would also help you with keeping trakt of what you have watched. And maybe wrong but think the idea was also to stream to Apple TV, Chromecast, etc.

**Comment by douglascamata** [comment]
@nordjac now I see a reason for this. Btw, do you know how PT fetched subtitles for drag 'n' dropped videos? I know that some sites use a hash of the video (uploader needs to point the video file for the hash calculation before upload), so the users get the exact subtitles for that release (this is awesome I can just drag and drop a file in the website and booom, perfect subtitles). Maybe we can do something like this, if we dont yet. :P

**Comment by xaiki** [comment]
it's a good idea  for future futures.

**Comment by vankasteelj** [comment]
fixed for the "it doesn't work". 

to implement hashing, it's already supported by my https://github.com/vankasteelj/opensubtitles-api and should even be already in butter as "giving the video path to the module will automatically calculate video hash before requesting subs". You can check by debugging.

As for wireless streaming, I think it's not really doable (only with a few codecs supported by the casts), but there's https://github.com/acidhax/streaming-media-encoder that might come in handy, it's an api for ffmpeg in JS. Plus side: you can use ffmpeg to recode on-the-fly. Downside: you need power + ffmpeg binaries

**Comment by alecive** [comment]
@vankasteelj If I got it correctly, you allowed d&d for magnet/torrents, wheras @giacomocerquone was talking about d&d videos. If so, we should reopen the issue.

**Comment by vankasteelj** [comment]
Nope, it works:

![nw_2016-02-03_03-16-59](https://cloud.githubusercontent.com/assets/12599850/12770877/9f0108ea-ca24-11e5-9bd9-0521636545c9.png)

But the choice of using raw unmodified nwjs, without any embded codecs, makes it near impossible to play a file, except if the exact codec was used to encode (the screenshot is using a modified 12.2 build of nwjs, with codecs)
