### ISSUE TITLE
Creating binaries

### ISSUE THREAD

**Issue by eikooc** [butterproject/butter-desktop#127]
Hey I just wanted to know how you plan to go about creating installers/binaries for windows, linux, mac osx and so forth?

**Comment by douglascamata** [comment]
@eikooc Hello, we are still working on replacing everything that is illegal with completely legal stuff. Until we don't finish this and do some polishing we can't upload official binaries and installers to the website. :/

**Comment by streger** [comment]
Windows will probably uses nsis installer, and for mac there will be a .dmg file, linux will probably have binaries inside .tar.gz

**Comment by eikooc** [comment]
@douglascamata Yes okay, I was just wondering about the workflow which @streger mentioned. @streger how do you plan on wrapping the tasks? I was just wondering because other electron projects have ongoing discussions as how to best create the binaries for all the platforms.

EDIT: (Okay I just saw that this repo is using nwjs and the butter-desktop-angular uses electron). Can you link this issue to that repository so I don't pollute this one? :-)

**Comment by streger** [comment]
@eikooc Just close this and reopen there (when needed), since this is totally different question there because it's still under development and installer isn't yet even imagined.
