### ISSUE TITLE
Dropping magnet urls doesn't seem to be working for me

### ISSUE THREAD

**Issue by vivek1729** [butterproject/butter-desktop#137]
So I cloned the master branch and am able to run butter-desktop. However, I tried dropping a magnet url on screen and it gets stuck at the "Connecting.." screen after resolving the torrent. In console as well I just get "Loading Torrent" as a message and nothing seems to be happening after that. Any idea on how to debug this to get the magnet urls to work as they used to in PopCorn Time. Anyone facing a similar issue, any help is appreciated :)

**Comment by kisPocok** [comment]
I have the same experience. In my case, `Streamer.start` gets a string (`/var/folders/[...]/T/Butter/TorrentCache/somehash.torrent`) instead of an object with torrent url or magnet properties. This causes the never ending loop.

**Comment by vivek1729** [comment]
Yes, you're right. The state doesn't update itself. However, earlier I thought, the app is not able to handle magnet urls at all but that's not the case. So if you change the api response and send a magnet url instead of a `.torrent` url, the streaming works. Why is that the case?

**Comment by xaiki** [comment]
DO NOT RE-ENABLE TORRENT COLLECTIONS IN BUTTER,
not for now, not without making it modular.
thank you.
