### ISSUE TITLE
Impossible to play videos

### ISSUE THREAD

**Issue by kuboosoft** [butterproject/butter-desktop#143]
Hi, I have compiled Butter fine in Linux, Fedora 22; but the problem doesn't play none video. Yes Butter is very premature but I share the complete log and screenshot.
https://gist.github.com/kuboosoft/24b4d035344b6f2f47be

Format: ![Alt Text](http://s24.postimg.org/6m58d9mol/butter.png)

**Comment by xaiki** [comment]
as you can see we're working on it...

**Comment by kuboosoft** [comment]
@xaiki but maybe my log helps to butter ;)

**Comment by Shuunen** [comment]
I have the same on Windows 7 

![image](https://cloud.githubusercontent.com/assets/439158/10953396/20ee3b3a-8348-11e5-9cbb-09509d86b666.png)
