### ISSUE TITLE
Custom list of trackers

### ISSUE THREAD

**Issue by eagleusb** [butterproject/butter-desktop#144]
Instead of using hardcoded list of trackers, can we have a selectable list and the ability to add our own ?

Thanks,

https://github.com/butterproject/butter-desktop/blob/320a67197e6b7aac96525d0ffe96ef9b4f18d756/src/app/lib/streamer.js#L81

**Comment by douglascamata** [comment]
@grumpycatt good point. I came to the conclusion that I don't know how getting trackers for a torrent works. I thought torrent files already had trackers information, but how would magnet links for torrent add tracker information as well?

**Comment by grumpycatt** [comment]
I will install a testbed and look into these questions (magnet vs torrent protocol). I'll get back to you ASAP

**Comment by rom1504** [comment]
torrents and magnet (can) contain a list of trackers.
The ones linked there are the default ones.

**Comment by vankasteelj** [comment]
the `trackers` arg is:

>Allows to declare additional custom trackers to use

Which means, I think, whether or not your torrent/magnet have trackers, it'll also ping those if needed (ex: if the provided trackers are offline, not working, or simply none is provided).

This line can be changed pretty easely (and made in an option), although Demonii should anyway be removed as it will go offline (or already is? I read something about it on TF). But I think it's not really important as those will only be used if the base material (magnet/torrent) trackers don't work.

**Comment by vankasteelj** [comment]
I opened Settings.trackers Object, containing atm:

Settings.trackers.forced and Settings.trackers.blacklisted

Those are used for magnet health calculation. It might be worth using the forced ones in streamer too, then have an option (at some point...) to change that 'forced' list.

**Comment by xaiki** [comment]
great addition !
