### ISSUE TITLE
Error grunt start

### ISSUE THREAD

**Issue by mo5tlef** [butterproject/butter-desktop#147]
user@dell MINGW64 ~/a (master)
$ grunt start
Running "start" task

Running "exec:win64" (exec) task
>> [6924:1031/224402:ERROR:nw_shell.cc(336)] ReferenceError: vjs is not defined
>>     at app://host/src/app/vendor/videojshooks.js:1:1
>> [6924:1031/224402:ERROR:nw_shell.cc(336)] ReferenceError: videojs is not defined
>>     at app://host/src/app/vendor/videojsplugins.js:3:1
>> [6924:1031/224402:ERROR:nw_shell.cc(336)] ReferenceError: jQuery is not defined
>>     at app://host/src/app/lib/jquery.plugins.js:36:4
>> [6924:1031/224402:ERROR:nw_shell.cc(336)] ReferenceError: Backbone is not defined
>>     at app://host/src/app/app.js:60:15
>> [6924:1031/224402:ERROR:nw_shell.cc(336)] TypeError: Cannot set property 'Config' of undefined
>>     at app://host/src/app/lib/config.js:223:16
>>     at app://host/src/app/lib/config.js:224:3
>> [6924:1031/224402:ERROR:nw_shell.cc(336)] TypeError: Cannot set property 'Updater' of undefined
>>     at app://host/src/app/updater.js:412:17
>>     at app://host/src/app/updater.js:414:3
>> [6924:1031/224402:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'vent' of undefined
>>     at app://host/src/app/httpapi.js:755:8
>>     at app://host/src/app/httpapi.js:767:3
>> [6924:1031/224402:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'Localization' of undefi          ned
>>     at app://host/src/app/language.js:26:4
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'vent' of undefined
>>     at app://host/src/app/lib/streamer.js:496:8
>>     at app://host/src/app/lib/streamer.js:501:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] ReferenceError: Backbone is not defined
>>     at app://host/src/app/lib/device/generic.js:6:18
>>     at app://host/src/app/lib/device/generic.js:163:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'Device' of undefined
>>     at app://host/src/app/lib/device/airplay.js:5:25
>>     at app://host/src/app/lib/device/airplay.js:53:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] Error: Cannot find module './lib/Browser'
>>     at Function.Module._resolveFilename (module.js:327:15)
>>     at Function.Module._load (module.js:264:25)
>>     at Module.require (module.js:356:17)
>>     at require (module.js:375:17)
>>     at Object.<anonymous> (C:\Users\user\a\node_modules\nodecast-js\index.js:3:18)
>>     at Module._compile (module.js:451:26)
>>     at Object.Module._extensions..js (module.js:469:10)
>>     at Module.load (module.js:346:32)
>>     at Function.Module._load (module.js:301:12)
>>     at Module.require (module.js:356:17)
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'Device' of undefined
>>     at app://host/src/app/lib/device/chromecast.js:5:25
>>     at app://host/src/app/lib/device/chromecast.js:167:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'Device' of undefined
>>     at app://host/src/app/lib/device/ext-player.js:5:25
>>     at app://host/src/app/lib/device/ext-player.js:265:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] ReferenceError: Backbone is not defined
>>     at app://host/src/app/lib/subtitle/generic.js:96:21
>>     at app://host/src/app/lib/subtitle/generic.js:226:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'Subtitles' of undefined
>>     at app://host/src/app/lib/subtitle/server.js:87:8
>>     at app://host/src/app/lib/subtitle/server.js:88:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] ReferenceError: Backbone is not defined
>>     at app://host/src/app/lib/models/filter.js:4:18
>>     at app://host/src/app/lib/models/filter.js:21:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] ReferenceError: Backbone is not defined
>>     at app://host/src/app/lib/models/movie.js:4:17
>>     at app://host/src/app/lib/models/movie.js:29:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'Model' of undefined
>>     at app://host/src/app/lib/models/show.js:4:19
>>     at app://host/src/app/lib/models/show.js:22:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] ReferenceError: Backbone is not defined
>>     at app://host/src/app/lib/models/generic_collection.js:4:25
>>     at app://host/src/app/lib/models/generic_collection.js:159:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'Model' of undefined
>>     at app://host/src/app/lib/models/movie_collection.js:4:30
>>     at app://host/src/app/lib/models/movie_collection.js:18:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] ReferenceError: Backbone is not defined
>>     at app://host/src/app/lib/models/stream_info.js:4:22
>>     at app://host/src/app/lib/models/stream_info.js:97:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'Model' of undefined
>>     at app://host/src/app/lib/models/show_collection.js:4:29
>>     at app://host/src/app/lib/models/show_collection.js:16:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'Model' of undefined
>>     at app://host/src/app/lib/models/anime_collection.js:4:30
>>     at app://host/src/app/lib/models/anime_collection.js:16:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'Model' of undefined
>>     at app://host/src/app/lib/models/indie_collection.js:4:30
>>     at app://host/src/app/lib/models/indie_collection.js:16:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] ReferenceError: Backbone is not defined
>>     at app://host/src/app/lib/models/favorite_collection.js:4:30
>>     at app://host/src/app/lib/models/favorite_collection.js:70:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'Model' of undefined
>>     at app://host/src/app/lib/models/watchlist_collection.js:4:34
>>     at app://host/src/app/lib/models/watchlist_collection.js:17:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] ReferenceError: Backbone is not defined
>>     at app://host/src/app/lib/models/notification.js:4:24
>>     at app://host/src/app/lib/models/notification.js:44:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'Config' of undefined
>>     at app://host/src/app/lib/cache.js:4:20
>>     at app://host/src/app/lib/cache.js:132:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot set property 'CacheV2' of undefined
>>     at app://host/src/app/lib/cachev2.js:132:17
>>     at app://host/src/app/lib/cachev2.js:134:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'Providers' of undefined
>>     at app://host/src/app/lib/providers/generic.js:70:8
>>     at app://host/src/app/lib/providers/generic.js:74:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'Providers' of undefined
>>     at app://host/src/app/lib/providers/cache_provider.js:47:8
>>     at app://host/src/app/lib/providers/cache_provider.js:48:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'Providers' of undefined
>>     at app://host/src/app/lib/providers/cache_providerv2.js:42:8
>>     at app://host/src/app/lib/providers/cache_providerv2.js:43:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'Providers' of undefined
>>     at app://host/src/app/lib/providers/trakttv.js:53:26
>>     at app://host/src/app/lib/providers/trakttv.js:717:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'Providers' of undefined
>>     at app://host/src/app/lib/providers/vodo.js:15:23
>>     at app://host/src/app/lib/providers/vodo.js:206:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'Providers' of undefined
>>     at app://host/src/app/lib/providers/archive.js:245:8
>>     at app://host/src/app/lib/providers/archive.js:247:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'Providers' of undefined
>>     at app://host/src/app/lib/providers/favorites.js:186:8
>>     at app://host/src/app/lib/providers/favorites.js:188:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'Providers' of undefined
>>     at app://host/src/app/lib/providers/watchlist.js:4:20
>>     at app://host/src/app/lib/providers/watchlist.js:205:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'Providers' of undefined
>>     at app://host/src/app/lib/providers/opensubtitles.js:35:8
>>     at app://host/src/app/lib/providers/opensubtitles.js:37:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'settings' of undefined
>>     at app://host/src/app/lib/providers/torrent_cache.js:10:31
>>     at app://host/src/app/lib/providers/torrent_cache.js:285:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] ReferenceError: Backbone is not defined
>>     at app://host/src/app/lib/views/title_bar.js:11:20
>>     at app://host/src/app/lib/views/title_bar.js:108:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] ReferenceError: Backbone is not defined
>>     at app://host/src/app/lib/views/main_window.js:6:22
>>     at app://host/src/app/lib/views/main_window.js:560:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'View' of undefined
>>     at app://host/src/app/lib/views/movie_detail.js:4:8
>>     at app://host/src/app/lib/views/movie_detail.js:387:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] ReferenceError: Backbone is not defined
>>     at app://host/src/app/lib/views/show_detail.js:9:22
>>     at app://host/src/app/lib/views/show_detail.js:848:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] ReferenceError: Backbone is not defined
>>     at app://host/src/app/lib/views/settings_container.js:9:20
>>     at app://host/src/app/lib/views/settings_container.js:765:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] ReferenceError: Backbone is not defined
>>     at app://host/src/app/lib/views/init_modal.js:4:21
>>     at app://host/src/app/lib/views/init_modal.js:55:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] ReferenceError: Backbone is not defined
>>     at app://host/src/app/lib/views/disclaimer.js:4:27
>>     at app://host/src/app/lib/views/disclaimer.js:33:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] ReferenceError: Backbone is not defined
>>     at app://host/src/app/lib/views/about.js:4:17
>>     at app://host/src/app/lib/views/about.js:67:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] ReferenceError: Backbone is not defined
>>     at app://host/src/app/lib/views/torrent_collection.js:8:29
>>     at app://host/src/app/lib/views/torrent_collection.js:417:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] ReferenceError: Backbone is not defined
>>     at app://host/src/app/lib/views/file_selector.js:7:24
>>     at app://host/src/app/lib/views/file_selector.js:201:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] ReferenceError: Backbone is not defined
>>     at app://host/src/app/lib/views/help.js:5:16
>>     at app://host/src/app/lib/views/help.js:52:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] ReferenceError: Backbone is not defined
>>     at app://host/src/app/lib/views/issue.js:8:17
>>     at app://host/src/app/lib/views/issue.js:270:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] ReferenceError: Backbone is not defined
>>     at app://host/src/app/lib/views/keyboard.js:4:20
>>     at app://host/src/app/lib/views/keyboard.js:29:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'View' of undefined
>>     at app://host/src/app/lib/views/notification.js:4:8
>>     at app://host/src/app/lib/views/notification.js:50:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] ReferenceError: Backbone is not defined
>>     at app://host/src/app/lib/views/player/loading.js:4:19
>>     at app://host/src/app/lib/views/player/loading.js:281:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] ReferenceError: Backbone is not defined
>>     at app://host/src/app/lib/views/player/player.js:13:18
>>     at app://host/src/app/lib/views/player/player.js:921:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] ReferenceError: Backbone is not defined
>>     at app://host/src/app/lib/views/browser/generic_browser.js:12:22
>>     at app://host/src/app/lib/views/browser/generic_browser.js:137:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'View' of undefined
>>     at app://host/src/app/lib/views/browser/movie_browser.js:4:27
>>     at app://host/src/app/lib/views/browser/movie_browser.js:13:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'View' of undefined
>>     at app://host/src/app/lib/views/browser/filter_bar.js:5:8
>>     at app://host/src/app/lib/views/browser/filter_bar.js:476:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] ReferenceError: Backbone is not defined
>>     at app://host/src/app/lib/views/browser/item.js:7:16
>>     at app://host/src/app/lib/views/browser/item.js:476:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] ReferenceError: Backbone is not defined
>>     at app://host/src/app/lib/views/browser/list.js:24:21
>>     at app://host/src/app/lib/views/browser/list.js:507:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'View' of undefined
>>     at app://host/src/app/lib/views/browser/show_browser.js:4:26
>>     at app://host/src/app/lib/views/browser/show_browser.js:13:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'View' of undefined
>>     at app://host/src/app/lib/views/browser/anime_browser.js:4:27
>>     at app://host/src/app/lib/views/browser/anime_browser.js:14:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'View' of undefined
>>     at app://host/src/app/lib/views/browser/indie_browser.js:4:27
>>     at app://host/src/app/lib/views/browser/indie_browser.js:14:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'View' of undefined
>>     at app://host/src/app/lib/views/browser/favorite_browser.js:4:30
>>     at app://host/src/app/lib/views/browser/favorite_browser.js:13:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'View' of undefined
>>     at app://host/src/app/lib/views/browser/watchlist_browser.js:4:31
>>     at app://host/src/app/lib/views/browser/watchlist_browser.js:9:3
>> [6924:1031/224403:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'start' of undefined
>>     at app://host/src/app/bootstrap.js:3:8
>>     at app://host/src/app/bootstrap.js:4:3

**Comment by kisPocok** [comment]
Please, send us your `node -v`.
I also have a silly question for you: Did you run `npm install` or even `bower install`?

**Comment by marclundgren** [comment]
@kisPocok which version of node should we use for this project?

**Comment by CristianOliveiraDaRosa** [comment]
node v0.10.25 here and same problem.

**Comment by CristianOliveiraDaRosa** [comment]
Using node v4.2.1 works well.  
:+1:  :ok_hand:

**Comment by MrAdder** [comment]
@mo5tlef Update your Node and Try again

**Comment by kisPocok** [comment]
@marclundgren *Working on Butter Core Pre-requisites: Node 0.10.x* copied from here https://github.com/butterproject/butter-desktop/blob/master/CONTRIBUTING.md#working-on-butter-core

**Comment by mo5tlef** [comment]
The problem has been resolved ( Update Node ) 
thank you all
