### ISSUE TITLE
Traffic Encryption?

### ISSUE THREAD

**Issue by AngelofSilence** [butterproject/butter-desktop#161]
In popcorntime, there was no way to encrypt the bittorrent traffic so that an ISP can't see what's being downloaded. Can that be added to butter?

**Comment by streger** [comment]
Hardly, it's not yet implemented in in torrent software Butter uses. Check https://github.com/mafintosh/torrent-stream/issues/55

**Comment by xaiki** [comment]
if you're interested in adding encryption to torrent-stream or helping switching to webtorrent we are interested =D

**Comment by vladionescu** [comment]
@xaiki what is the timeline for switching to webtorrent? That project is currently alpha (is this acceptable to Butter Project?).

I'm willing to help the transition.

**Comment by Draxler** [comment]
@vladionescu

:+1:  :100:

**Comment by gsiotas** [comment]
:+1:

**Comment by christopherturner** [comment]
@vladionescu 👍

**Comment by albabosh** [comment]
Webtorrent does not encrypt traffic, it adds a new protocol

**Comment by albabosh** [comment]
Any peer in the swarm can see what is being downloaded, either with encryption or without.

**Comment by vankasteelj** [comment]
I second @albabosh 's statement: there is no other way of hiding from peers than using a VPN.
