### ISSUE TITLE
Errors running "grunt start" osX

### ISSUE THREAD

**Issue by gsantome** [butterproject/butter-desktop#165]
Hello guys... long life to PopCorn or Butter now... 

I'm having an issue when I tried to installed everything on my mac... npm and grunt runs without problem... but when i tried "grunt start" im getting a lot of errors...

<img width="1254" alt="screen shot 2015-11-04 at 10 34 21 am" src="https://cloud.githubusercontent.com/assets/2914973/10934384/da1a123c-82df-11e5-840f-b77ea6f3509d.png">

I need help to solve this problems...

Thanks!

**Comment by xaiki** [comment]
please take user errors to discuss.butterproject.org
