### ISSUE TITLE
kat-api dependency unavailable

### ISSUE THREAD

**Issue by bdpdx** [butterproject/butter-desktop#175]
butter requires `kat-api` which seems to have been hosted at popcorntime.io and is no longer installable by npm.  Would someone who has this dependency available please add it to the butter source?

**Comment by douglascamata** [comment]
`kat_api` isn't supposed to be present in Butter (at least in the official release) because it has legal problems.

**Comment by bdpdx** [comment]
Is there a way to disable it then, or are you aware of an unofficial mirror?  At the moment butter won't build without it.

**Comment by douglascamata** [comment]
Well, you can remove it from the dependencies and remove all the related code in the source and it should be okay. It's not even used in the app itself.

**Comment by janjaap** [comment]
Is `kat-api` replaceable by [`kat-api-json`](https://www.npmjs.com/package/kat-api-json)?

**Comment by pelewin** [comment]
It's working now

**Comment by shaneonabike** [comment]
Well it's still there in the package.json as a dependency... unless people are using another branch?

**Comment by jeovanevs** [comment]
I'm with the same problem. How do you solved it?

**Comment by mnzt** [comment]
@jeovanevs your question has already been answered. Please read prior comments.

**Comment by arnaldorusso** [comment]
Hi @jeovanevs 
I have solved this issue, by modifying the package.json
line referred as `kat-api`, substituting to `kat-api-json` and removing version.
Did you do the same @mnzt ?
I have also changed the incompatible version of `nedb` which is pointed out to 1.4.1, but it seems to not exist. So I fixed to 1.4.0

I have completed instaled it on my Debian, but unfortunately Butter it's not working properly.

**Comment by MrAdder** [comment]
https://github.com/butterproject/butter-desktop/commit/55466c99aef0ba87609febde8c9dc87f5c6abc10 Removed the KAT-API as it was no longer needed
