### ISSUE TITLE
Question: Which /paths to copy from?

### ISSUE THREAD

**Issue by Geyup** [butterproject/butter-desktop#179]
Hi,

When compiling from source there are two /paths;

/build/butter/linux64
and
/cache/0.12.3/linux64

Both have ```icudtl.dat``` ```libffmpegsumo.so``` ```nw.pak```

So which path do I want to copy from, or does it matter?

Also in ```/cache/0.12.3/linux64``` it has some additional files; ```nw``` and ```nwjc``` should I keep those also included with Butter?

With Popcorn-Time I've only used these files listed below, so not sure if Butter is just the same?

icudtl.dat
libffmpegsumo.so
nw.pak
package.nw
locales

Thanks

**Comment by Geyup** [comment]
Can I please get a reply?

thank you

**Comment by MrAdder** [comment]
/build/butter/linux64

**Comment by Geyup** [comment]
thank you
