### ISSUE TITLE
Movie Posters Missing...

### ISSUE THREAD

**Issue by Geyup** [butterproject/butter-desktop#180]
I just cloned from github yesterday and compiled it from source in Slackware.

When I run Butter, a lot of the movies are missing posters, is this a known problem, or something I can do to get them to load?

Have a look at the screen shot;

http://i.imgur.com/nfc66M3.jpg

**Comment by MrAdder** [comment]
Its a possibility that those movies do not have posters I will look into this tho

**Comment by Geyup** [comment]
ok great...
