### ISSUE TITLE
CMake Error: -- Configuring incomplete, errors occurred!

### ISSUE THREAD

**Issue by Geyup** [butterproject/butter-desktop#186]
I noticed at the terminal when I was compiling this output;

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBVLC_LIBRARY
    linked by target "libvlc_wrapper" in directory /tmp/butter/Butter-11.13.15/node_modules/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/deps/libvlc_wrapper

-- Configuring incomplete, errors occurred!
See also "/tmp/butter/Butter-11.13.15/node_modules/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/build/CMakeFiles/CMakeOutput.log".
ERR! OMG Process terminated: 1
Unhandled rejection Error: Process terminated: 1
    at ChildProcess.<anonymous> 
(/tmp/butter/Butter-11.13.15/node_modules/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/node_modules/cmake-js/lib/es5/cMake.js:741:18)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:820:12)
npm WARN cannot run in wd Butter@0.3.8-5a bower install --config.interactive=false && grunt setup (wd=/tmp/butter/Butter-11.13.15)
defer-request@0.0.2 node_modules/defer-request

I looked a little through the CMakeOutput.log but didn't really notice anything.

The compiling doesn't stop, it just spits this out and continues. The compile completed and butter seems to look and run ok, so not sure if there is really something wrong here?

Here's the CMakeOutput.log;

http://dpaste.com/3XGGGPF

**Comment by RSATom** [comment]
What OS do you use?

**Comment by MattMuffin** [comment]
I have the exact same issue, using ubuntu 15.10 on x64

**Comment by Geyup** [comment]
Sorry not using butter now...
