### ISSUE TITLE
kat-api@'>=0.0.0 <1.0.0'

### ISSUE THREAD

**Issue by Xenosz** [butterproject/butter-desktop#200]
$ npm install
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: kat-api@'>=0.0.0 <1.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["9999.9999.9999"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'Butter'
npm ERR! notarget

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Xenosz\Desktop\butter-desktop\npm-debug.log
[npm-debug.log.txt](https://github.com/butterproject/butter-desktop/files/39165/npm-debug.log.txt)

**Comment by toXel** [comment]
+1

**Comment by surdu** [comment]
Looks like kat-api npm package was taken down, along with other packages from the author:

https://www.npmjs.com/~isaacs

**Comment by timurkalandarov** [comment]
+1

**Comment by leocaseiro** [comment]
:+1:

**Comment by leocaseiro** [comment]
In alternative there is the repo kat-api-json, I'm not sure if it'll work https://github.com/isdampe/kat-api

**Comment by MrAdder** [comment]
I will be fixing the Kat-API issue shortly
