### ISSUE TITLE
Many errors running 'npm install' 

### ISSUE THREAD

**Issue by orjanj5** [butterproject/butter-desktop#207]
$ npm install
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7

npm ERR! version not found: nedb@1.4.1
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\program files\Git\butter-desktop\npm-debug.log

I have no experience with this program nor any knowledge on how to fix this

**Comment by 96AA48** [comment]
Having the same issues over here. I checked out the npm for [`nedb`](http://npmjs.org/nedb) and it said that the latest version was `1.4.0` instead of `1.4.1`. Also `kat-api` seems to be deprecated as well. Shouldn't we change the `package.json` so that the "Getting Started" process is done flawlessly?

**Comment by orjanj5** [comment]
so i have to reinstall nedb with 1.4.0? and delete kat - api?

**Comment by 96AA48** [comment]
It worked for at least. Some other issues seem related to this. `kat-api` has been taken down to some extent. The application does compile after reinstalling `nedb` and deleting `kat-api`.

**Comment by Xenosz** [comment]
instead of using kat-api use kat-api-json with version "1.x.x"

**Comment by Xenosz** [comment]
still many errors though:

**Comment by lordoffreaks** [comment]
Same here, changing `"nedb": "1.4.1",` for `"nedb": "1.4.0",` fixed the problem

**Comment by Xenosz** [comment]
yeah got it to work now too, anybody know when more movies will be added? (or plugin to add movies will be created)
