### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by frnco** [butterproject/butter-desktop#209]
This is more of a milestone of an issue, but it was bothering me that it is not an issue here.

I believe Butter needs to track progress towards shipping binaries and set it as an objective, and not something far and ephemeral such as an milestone. Considering the implicit values of Butter being a completely free way for people to stream movies, I believe we are focusing to much on the "whats" and forgetting that, for it to be really free and available to people, it needs to be easily downloadable.

Now on that front, I think we should reference the issues that are impeditive (i.e., stuff that may be considered illegal or detrimental for the project) here, so we have a place to understand where we are in relation to binaries.

Obviously, as I'm not a maintainer and haven't contributed to butter yet (Though I intend to, and already cloned), I do understand if you guys dislike the idea, but if you do, please consider some way of tracking progress towards having binaries for at least some system ASAP, since the main focus should be to get the MVP up and running.

**Comment by NoNameProvided** [comment]
:+1: I like this.

I have showed Popcorn Time to a few friends of mine when I found it the first time. Since it stopped working they keep asking about it, I told them the successor is on the way and they are keep asking about it every week at least once. So people are excited about Butter, the Butter team definitely should set up some milestones to provide some info about the first release.

**Comment by MrAdder** [comment]
We will take this into consideration, now that I am not ill, I can look at doing this as soon as possible

**Comment by willejs** [comment]
Maybe we can build the binaries in travis ci and publish them to releases?

**Comment by frnco** [comment]
I believe solving the legal issues and getting to a working build is the priority.

I imagine sing a CI system would be nice but it's a further improvement, and not the primary objective.

**Comment by NoNameProvided** [comment]
@MrAdder  Any info on the first release?
