### ISSUE TITLE
Links in contribution guide broken

### ISSUE THREAD

**Issue by NicolasPio** [butterproject/butter-desktop#21]
In [CONTRIBUTING.md](https://github.com/butterproject/butter/blob/master/CONTRIBUTING.md) links for wiki is broken, wikis does not exist.

**Comment by MrAdder** [comment]
Will work with the team to get the Wiki Back Up and running

**Comment by xaiki** [comment]
will try to get back the wikis.

**Comment by NicolasPio** [comment]
If I can help, just talk

**Comment by napcae** [comment]
Solved with #91 afaik.

**Comment by mcoughlan19** [comment]
if i can help please let me know

**Comment by napcae** [comment]
You could write a draft for the mockup links that are existing right now. Look at other projects maybe and use them as a guide(?)

**Comment by vankasteelj** [comment]
https://github.com/butterproject/butter-desktop/issues/343
