### ISSUE TITLE
[Linux mint] make_butter.sh not starting

### ISSUE THREAD

**Issue by orjanj5** [butterproject/butter-desktop#214]
Make_butter.sh does not do anything when i try to start it. I am new to Linux and is testing my way through.

**Comment by stevelacy** [comment]
Did you get a fresh clone of butter from github?

Verify the output of: `ls -al make_butter.sh `
it should be: `-rwxr-xr-x 1 user user 5581 Nov 26 11:00 make_butter.sh`

**Comment by streger** [comment]
as @stevelacy already asked, if you haven't run Terminal and navigate to butter desktop folder and execute: `./make_butter.sh`
