### ISSUE TITLE
Can't join to OpenSubtitles

### ISSUE THREAD

**Issue by styx** [butterproject/butter-desktop#218]
```>> [23388:1127/203612:INFO:CONSOLE(21)] ""%c[%cERROR%c] OpenSubtitles.login()" "color: black;" "color: red;" "color: black;" "414 Unknown User Agent"", source: app://host/src/app/app.js (21)```

The error is: ```"414 Unknown User Agent"```

**Comment by vankasteelj** [comment]
todo: 
- register a UserAgent for Butter.
- use it in settings_container.js & opensubtitles.js
