### ISSUE TITLE
run on browser

### ISSUE THREAD

**Issue by Alvarz** [butterproject/butter-desktop#220]
Hello guys you're doing a great job. I want to know how can i run butter directly from my browser like chrome?

**Comment by TheMightyCraken** [comment]
I dont think this is currently possible.

**Comment by Alvarz** [comment]
Yeah you're right, it can't be done

**Comment by albabosh** [comment]
Yes, you can. Try yify-pop project (it needs some modification to run well)

**Comment by Alvarz** [comment]
Yeah, there some project to achieve this, i has been playing with
peerflix-server, i'll dig on yify pop. However qhat we said its using
butter you cant do it but other peojects we can. Thanks for introduce me
this yify pop, looks great

**Comment by tusharmath** [comment]
https://github.com/feross/webtorrent might get this done.

**Comment by Alvarz** [comment]
yeah thanks!

**Comment by vankasteelj** [comment]
we rely on node for this desktop version, hence: no browser
