### ISSUE TITLE
Wcjs-player crashes when playing video

### ISSUE THREAD

**Issue by thepearldream** [butterproject/butter-desktop#226]
http://discuss.butterproject.org/t/wcjs-player-crashes-when-playing-video/529

**Comment by MrAdder** [comment]
I am only having this issue with Archive.ORG Videos

**Comment by thepearldream** [comment]
I have the issue with all videos including drag and droping a video. I will debug some more to see if there is something special with my setup.

**Comment by thepearldream** [comment]
I found a similar issue: https://github.com/jaruba/wcjs-player/issues/2. I am running on a mac.

**Comment by thepearldream** [comment]
I found this error that happens when the player crashes: 

""%c[%cERROR%c] Error: Cannot find module 'webchimera.js'" "color: black;" "color: red;" "color: black;" "Error: Cannot find module 'webchimera.js'\n    at Function.Module._resolveFilename (module.js:327:15)\n    at Function.Module._load (module.js:264:25)\n    at Module.require (module.js:356:17)\n    at require (module.js:375:17)\n    at Object.module.exports.init (/Users/franco/Documents/butter-desktop/node_modules/wcjs-player/node_modules/wcjs-renderer/index.js:147:30)\n    at wjs.addPlayer (/Users/franco/Documents/butter-desktop/node_modules/wcjs-player/index.js:457:87)\n    at Backbone.Marionette.ItemView.extend.onShow (app://host/src/app/lib/views/player/player.js:226:66)\n    at Object._triggerMethod (app://host/src/app/vendor/marionette/lib/backbone.marionette.js:685:25)\n    at Marionette.View.Backbone.View.extend.triggerMethod (app://host/src/app/vendor/marionette/lib/backbone.marionette.js:1939:28)\n    at Object.Marionette.triggerMethodOn (app://host/src/app/vendor/marionette/lib/backbone.marionette.js:721:16)\n    at Marionette.Region.Marionette.Object.extend.show (app://host/src/app/vendor/marionette/lib/backbone.marionette.js:1189:20)\n    at Backbone.Marionette.LayoutView.extend.showPlayer (app://host/src/app/lib/views/main_window.js:492:25)\n    at triggerEvents (app://host/src/app/vendor/backbone/backbone.js:369:57)\n    at triggerApi (app://host/src/app/vendor/backbone/backbone.js:356:19)\n    at eventsApi (app://host/src/app/vendor/backbone/backbone.js:155:16)\n    at Events.trigger (app://host/src/app/vendor/backbone/backbone.js:346:5)"", source: app://host/src/app/app.js (21)

**Comment by thepearldream** [comment]
Got to the bottom of this issue. There were 2 bugs:

1. webchimera.js fails to copy libvlc into the build/Release folder see: https://github.com/RSATom/WebChimera.js/issues/33. Explains "Library not found" error. Anyway we can package the right library or edit gruntfile?

2. webchimera.js was building for x64 when grunt was running mac:32. Explaining the "No suitable image found".

The "Could not find module" error was as a result of not building webchimera.js during npm install. I ignored the error about missing cmake on my machine. Facepalm.

**Comment by vankasteelj** [comment]
this is fixed on the test/wcjs branch, i'll link to https://github.com/butterproject/butter-desktop/issues/344
