### ISSUE TITLE
PowerPC no longer supported

### ISSUE THREAD

**Issue by thepearldream** [butterproject/butter-desktop#238]
OSX El Capitan

Steps to reproduce:
1. clone
2. npm install -g grunt-cli bower
3. npm install
4. grunt build
5. Execute from build folder. Icon will show a disabled icon - like the ghostbusters symbol!

**Comment by vankasteelj** [comment]
It never worked on PPC, I think? NWjs uses Webkit, which isn't friend with PowerPC.
