### ISSUE TITLE
When is butter going to release binaries?

### ISSUE THREAD

**Issue by nojvek** [butterproject/butter-desktop#278]
Some binaries to play around would be nice.

**Comment by xaiki** [comment]
when ready. please don't use github issue for user questions =)

**Comment by PokemonLegend2** [comment]
I would like to unsubscribe from this. Thank you



<div>-------- Original message --------</div><div>From: Niv Sardi <notifications@github.com> </div><div>Date:16/02/2016  4:00 PM  (GMT+10:30) </div><div>To: butterproject/butter-desktop <butter-desktop@noreply.github.com> </div><div>Subject: Re: [butter-desktop] When is butter going to release binaries? (#278) </div><div>
</div>
Closed #278.

---
Reply to this email directly or view it on GitHub:
https://github.com/butterproject/butter-desktop/issues/278#event-551538033

**Comment by bunster** [comment]
I thought it was a fair question. This waiting has taken _**ages**_ and there's still nothing to show? Better off just sticking with apps like [stremio](http://strem.io/) instead of waiting for something like butter which will never release by the looks of it.
