### ISSUE TITLE
https://popcorntime.sh/

### ISSUE THREAD

**Issue by NoNameProvided** [butterproject/butter-desktop#283]
Do we know anything about this? 

I just got an email saying the new popcorn time is here. 

> New Incident Status: Resolved
> Say Hello, To https://popcorntime.sh
> Feb 16, 15:56 UTC
>

**Comment by streger** [comment]
No, it has nothing to do with us. As with all other PT forks tread carefully.

**Comment by YIFYtorrents** [comment]
## popcorntime.sh is just a SCAM and it is NOT the official .io fork as they claim

dont fall into this bullshit

**Comment by xaiki** [comment]
please don't use github issues for general discution we have a forum for that.
that said the .sh fork is using butter as a base.

**Comment by Draxler** [comment]
@YIFYtorrents (another name you stole to decive people)
You are one big BS scamer! URLS in question are legit  and i didn't noticed Butter project choose you to be their spokesman.! You need to be in mental institutuion to help you find which is your real identety from all of these 100's of defferent's IDs you used..  
--------------
Butter project want to distance them selfs from PopcornTime we all know that but they want even more is to distance them self from YOU, becuase your are a cancer (with no cure)...
