### ISSUE TITLE
Many docs/ files are empty

### ISSUE THREAD

**Issue by 0tho** [butterproject/butter-desktop#298]
It will be harder to other people help the project without knowing how.

You mention "roadmap", "planned features" and "code standards" in "Contributing to Butter", but they are just placeholders

**Comment by vankasteelj** [comment]
Indeed, these are still resting on an old-now-disappeared wiki. And they all need to be rewritten entirely anyways. It's going to be a concern for us very soon, and we sadly can't really delegate that or wait for a PR as these are the very core of the entire app development.

Thanks for the report, it's good to have it displayed here!

**Comment by streger** [comment]
List of missing (for now):
 - Code Standards: https://github.com/butterproject/butter-desktop/tree/master/docs/Code-Standards.md
 - Building & Debugging: https://github.com/butterproject/butter-desktop/tree/master/docs/Build-Debug.md
 - Roadmap: https://github.com/butterproject/butter-desktop/blob/master/docs/RoadMap.md
 - Planned features: https://github.com/butterproject/butter-desktop/blob/master/docs/Planned-Features.md
 - #Git Workflow (incompleteˇ): https://github.com/butterproject/butter-desktop/tree/master/docs/Git-Workflow.md
- Clean-up history https://github.com/butterproject/butter-desktop/tree/master/docs/Git-Workflow.md#clean-up-history
- Check It Passes The Tests: https://github.com/butterproject/butter-desktop/blob/master/docs/Git-Workflow.md#check-it-passes-the-tests

Connected issue: #21

**Comment by 0tho** [comment]
It is also missing a link to the Butter Project trello board.
I could only find a link to that on the forums.

**Comment by vankasteelj** [comment]
I'll close here and let my multichecklistofzedead take over

https://github.com/butterproject/butter-desktop/issues/343
