### ISSUE TITLE
Watchlist not listing movies in Trakt watchlist

### ISSUE THREAD

**Issue by loris** [butterproject/butter-desktop#301]
I can work on a PR if this is something people want. It makes lots of sense to me, so I’m firstly wondering why it has been implemented this way.
According to the [watchlist code](https://github.com/butterproject/butter-desktop/blob/8c4f92125ad5cb4dc2a8840d48450f656758186c/src/app/lib/providers/watchlist.js#L26), it is using the [calendars/my/shows](http://docs.trakt.apiary.io/#reference/calendars/my-shows/get-shows) endpoint from the trakt API. It would makes more sense to use the [sync/watchlist](http://docs.trakt.apiary.io/#reference/sync/get-watchlist/get-watchlist) method, thus displaying both TV series and movies added to the trakt watchlist service.

**Comment by xaiki** [comment]
ideally this should be a provider, do you think you can work on porting current trakt code to be a butter-provider ?

**Comment by vankasteelj** [comment]
I've given you a headstart with https://github.com/vankasteelj/trakt.tv, instead of using the (bad) current trakttv.js file.

**Comment by vankasteelj** [comment]
And also this should be way more efficient than current watchlist.js (and it has movies):  http://hastebin.com/esetogucuh.coffee

**Comment by vankasteelj** [comment]
watchlist todo:

- [ ] do something about details
- [ ] display item for episode instead of show (maybe year replaced by episode info?)
- [ ] refresh watchlist when something has been watched
- [ ] move away from localStorage

**Comment by 0tho** [comment]
What do you plan to use instead of localstorage?

**Comment by vankasteelj** [comment]
we have a nedb already in place

**Comment by vankasteelj** [comment]
I'll open a new issue, there's to many todo
