### ISSUE TITLE
Any plans for using Electron as a base?

### ISSUE THREAD

**Issue by ZakariaRidouh** [butterproject/butter-desktop#303]
Hey Guys! I was just wondering if the core team had any plans to use Electron (https://github.com/electron/electron).
Thanks! :smile:

**Comment by sergei1152** [comment]
What advantages would using electron compared to nw.js bring? They're both pretty similar.

**Comment by xaiki** [comment]
yes, we do, it's better mantained and has double the threads (2).
plan is:
- migrate views to react via butter-components
- migrate core code to (TESTABLE) npm modules
- when we get to a 90% code reduction, switch to electron.

**Comment by iTsFILIPOficial** [comment]
@xaiki Any updates on changing it to electron?

**Comment by xaiki** [comment]
@iTsFILIPOficial todolist still holds =(

**Comment by amilajack** [comment]
I'm working on an experimental client here:

https://github.com/amilajack/popcorn-desktop-experimental

**Comment by xaiki** [comment]
@amilajack that is very interesting, have you seen our react components: https://github.com/buttercomponents ?

**Comment by vankasteelj** [comment]
ES6, Electron, webpack. Looks great man!

**Comment by amilajack** [comment]
@xaiki I found out about them after I created my own components.
@vankasteelj thanks!
