### ISSUE TITLE
Video playback into Butter doesn't work on Mac OSX

### ISSUE THREAD

**Issue by jefflai** [butterproject/butter-desktop#319]
After choosing to play a video in Butter, I get the error message "The video could not be loaded, either because the server or network failed or because the format is not supported". I tried multiple videos, and this is happening to all of them. However, when choosing to play in VLC, the video plays just fine.

I'm running Mac OSX El Capitan version 10.11.3 and node version 5.7.1

<img width="1280" alt="screen shot 2016-03-12 at 9 14 46 pm" src="https://cloud.githubusercontent.com/assets/478026/13727068/f5e03bea-e897-11e5-9d78-c67fa08df87a.png">

**Comment by xaiki** [comment]
we need to switch back to using popcorntime's build of node-webkit (or finish the wcjs work)

**Comment by jefflai** [comment]
which files in butter-desktop are related to wcjs?

**Comment by xaiki** [comment]
player.js, needs to be rewritten, there was a branch at some point

**Comment by vankasteelj** [comment]
@jefflai Should be fixed, please reopen if the issue still occurs
