### ISSUE TITLE
Will it be moved to npm?

### ISSUE THREAD

**Issue by kdpuvvadi** [butterproject/butter-desktop#320]
Is there any plan or possiblity to move to npm rather than grunt?

**Comment by ZakariaRidouh** [comment]
Do you mean move to npm rather than Bower? If so, look at #306.

Triggering everything with npm is all done over at PR #314 and all that's left is waiting on getting it merged :smile: 

If you have any ideas, feel free to submit a patch!

**Comment by vankasteelj** [comment]
I've done some tests with nwjs-prebuilt, and it works, but I don't like that it's storing nwjs binaries in `$HOME/.nwjs` rather than in the git repo. It doesn't make any sense, and you have to stick with official binaries, not custom ones.
