### ISSUE TITLE
.

### ISSUE THREAD

**Issue by YIFYtorrents** [butterproject/butter-desktop#323]

**Comment by streger** [comment]
jfc you should be banned from Earth. Stop this. Please.

**Comment by YIFYtorrents** [comment]
You didn't accept mod requests. You are either with use or u against us.

**Comment by streger** [comment]
you are so pathetic. such a waste of my time right now.
you're most typical troll ever. please go and find somewhere else to cry.

**Comment by YIFYtorrents** [comment]
What do you think about the money laundering insider information. I hope you like it
