### ISSUE TITLE
Can't run Butter on Cortex-A7 device

### ISSUE THREAD

**Issue by christianweinz** [butterproject/butter-desktop#328]
**Operating System Version:**
Linux 3.4.108-lime armv71 Debian Jessie

**Butter version:**
Up-to-date with git right now.

**Problem:**

> npm start

fails.

log: http://paste.debian.net/418113/

**Comment by xaiki** [comment]
the build process doesn't suport arm, but if you get a nw build for your plateform all the rest should work, are you interested in doing futher testing so wecan include arm to our build-chain ?

**Comment by christianweinz** [comment]
I am interesting in doing testing. Also, I would help with other things, if you point me to where to start.

**Comment by xaiki** [comment]
first test if it works, get a copy of nodewebkit 0.12.3 for your arch on their website and run it with `nw .` in the root of the source tree, if that works, look at Gruntfile.js you'll see that our plateforms are pretty hardcoded.

**Comment by vankasteelj** [comment]
update to tell you to look in gulpfile.js were you should pretty much only add a value to the array `availablePlatforms` for it to take it in account
