### ISSUE TITLE
butter starts as background process

### ISSUE THREAD

**Issue by nak0604** [butterproject/butter-desktop#330]
So, after double checking for dependencies and running the quickstart again, along with following the "If you encounter trouble with the above method, you can try:" section. Butter starts as a single background process and requests for network access. After that it duplicates the background process and does nothing. Ive noticed the longer i leave it the more background processes it makes.

![2016-03-23 14_56_43-task manager](https://cloud.githubusercontent.com/assets/4227228/13997244/93f42450-f107-11e5-8330-550f9327b53d.png)

**Comment by nak0604** [comment]
Deleted everything and built it again, now grunt start results in only 4 background processes (didnt request for network access) with no cpu activity.
![2016-03-23 15_17_41-settings](https://cloud.githubusercontent.com/assets/4227228/13997859/71881068-f10a-11e5-86c3-270c00e6a71b.png)

**Comment by xaiki** [comment]
at this stage we're going to need more dev-centred issues here, for user-issues please see the forums.
