### ISSUE TITLE
Butter Desktop Angular deveopment

### ISSUE THREAD

**Issue by ZakariaRidouh** [butterproject/butter-desktop#337]
Hey Guys!

I'm extremely interested in continuing development of the [butter-desktop-angular](https://github.com/butterproject/butter-desktop-angular) project and would love to ask if the core team would allow me to continue its development and would allow me to take over the project.
 
This decision came after I saw much potential in the Angular rewrite and as I am currently learning AngularJS and am having very much fun with it. I would love to use this awesome project to help me very much with my programing experience. :smile_cat: 

Thank you all so very much!
:smile: Cheers!

**Comment by xaiki** [comment]
please do so, it's currently unmaintained
