### ISSUE TITLE
nwjs >= 0.18.0

### ISSUE THREAD

**Issue by vankasteelj** [butterproject/butter-desktop#339]
- [x] build nwjs with codecs (or build only libffmpeg for each platform, but what about AVI?)
- [x] port code to 0.18
  - [x] Gulpfile
  - [x] Package.json
  - [x] Trakt/TVst new window

See branch _update/nw18_

Updating nwjs isn't trivial, but it can lead to a better software.

So far, the advantages there are to switch to >= 0.13.x are:
- compatibility with chrome extensions (chromecast, anyone?)
- better font-hinting
- drag&drop correctly working on linux
- generally a little faster
- security fixes
- more recent iojs

NOTE: no need for codecs if we use wcjs

**Comment by vankasteelj** [comment]
On linux Ubuntu x64 (14.04, 14.10, 15.04): supports h264, some avi, mp3

You can download entire zip package of chromium.src from Github (https://github.com/nwjs/chromium.src ~800M), which is much smaller than syncing entire NW source tree. Extract the ZIP to a local folder and follow the instructions below to download additional dependencies.

#############

Install dependencies with build/install-build-deps.sh

	cd <folder>
	sudo echo
	./build/install-build-deps.sh

#############

Minimal requirements:

1) base/allocator/: Windows only
2) build/*
  - build/linux/*-sysroot/*: Linux Only. Use `build/linux/sysroot_scripts/install-sysroot.py --running-as-hook` to fetch build dependencies for Linux (~100M)
3) tools/*
  - <tools>/gyp: see DEPS for commit and repo
4) third_party/yasm
  - <yasm>/sources/patched-yasm: see DEPS for commit and repo
5) third_party/ffmpeg: see DEPS for commit and repo
6) third_party/llvm-build: Mac and Linux only. Use `tools/clang/scripts/update.py --if-needed` to download.

DEPS for commit and repo = in the file ./DEPS, find the variables, and: 

	git clone <repo>
	cd <folder>
	git reset --hard <commit>

############

Add the codecs desired to the configuration file:

	cd third_party/ffmpeg/

Go to (/third_party/ffmpeg)/chromium/scripts/build_ffmpeg.py and change the line "# Google Chrome & ChromeOS specific configuration." and below, to add:
- decoder: hevc,eac3,ac3
- demuxer: dtshd,dts

Save the file, and recompile the configuration files:

	./chromium/scripts/build_ffmpeg.py linux x64 --config-only

Build ChromeOS:

	cd build.x64.linux/ChromeOS
	make
	cd ../..

Copy the configurations:

	./chromium/scripts/copy_config.sh 

Generate GYP files:

	./chromium/scripts/generate_gyp.py

############

With sources above, you can now generate build targets with gyp:

	cd ../..
	export GYP_GENERATORS=ninja
	export GYP_DEFINES="ffmpeg_branding=ChromeOS component=shared_library"
	export PYTHONPATH="$PWD/build"
	rm -rf out/* && ./tools/gyp/gyp -I build/common.gypi --depth=. ./third_party/ffmpeg/ffmpeg.gyp

On Windows, GYP_DEFINES should also include clang=0 to disable clang.

(note: using branding=ChromeOS activates the .avi compatibility)
############

Build ffmpeg with ninja:

	ninja -C out/Release ffmpeg

You will find build results in out/Release.

**Comment by vankasteelj** [comment]
Ok, so, the above doesn't work. Let's try with a complete NWjs custom build:

On linux Ubuntu x64 (14.04, 14.10, 15.04)

_note: 15.10 works if you bypass build/install-build-deps.sh and manually find the required deps_


############

Generate .gclient for NW.js source code:

	mkdir -p $HOME/nwjs
	cd $HOME/nwjs
	gclient config --name=src https://github.com/nwjs/chromium.src.git@origin/nw13

Generally if you are not interested in running Chromium tests, you don’t have to sync the test cases and reference builds, which saves you lot of time. Open the .gclient file you just created and replace custom_deps section with followings:

	"custom_deps" : {
	    "src/third_party/WebKit/LayoutTests": None,
	    "src/chrome_frame/tools/test/reference_build/chrome": None,
	    "src/chrome_frame/tools/test/reference_build/chrome_win": None,
	    "src/chrome/tools/test/reference_build/chrome": None,
	    "src/chrome/tools/test/reference_build/chrome_linux": None,
	    "src/chrome/tools/test/reference_build/chrome_mac": None,
	    "src/chrome/tools/test/reference_build/chrome_win": None,
	},

############

A) sync the sources (~5000M): !WARNING! IF IT'S THE 1ST TIME YOU SYNC, SEE BELOW

	gclient sync --with_branch_heads
	

B) for a first-time build on linux:

  B1) sync the sources:

	gclient sync --with_branch_heads --nohooks

  B2) then install dependencies with build/install-build-deps.sh

	sudo echo
	./build/install-build-deps.sh

############

Set GYP env:

	cd src/
	export GYP_GENERATORS=ninja
	export GYP_DEFINES="nwjs_sdk=1 disable_nacl=0 ffmpeg_branding=Chrome ffmpeg_component=shared_library proprietary_codecs=1 enable_hevc_demuxing=1 enable_ac3_eac3_audio_demuxing=1"
	export PYTHONPATH="$PWD/build"

#############

Add the codecs desired to the configuration file:

	cd third_party/ffmpeg/

Go to (/third_party/ffmpeg)/chromium/scripts/build_ffmpeg.py and change the line "# Google Chrome & ChromeOS specific configuration." and below, to add:
>'--enable-decoder=aac,hevc,eac3,ac3,h264,mp3',
>'--enable-demuxer=aac,mp3,mov,dtshd,dts',
>'--enable-parser=aac,h264,mpegaudio',

Save the file, and recompile the configuration files:

	./chromium/scripts/build_ffmpeg.py linux x64 --config-only

##############

Build ffmpeg for ChromeOS:

	cd build.x64.linux/ChromeOS
	make


Trick nwjs into thinking it's Chrome (and not ChromeOS):

	cd ..
	rm -r Chrome
	cp -R ChromeOS Chrome
	cd ..

Copy the new ffmpeg configurations:

	./chromium/scripts/copy_config.sh 

Generate ffmpeg GYP files:

	./chromium/scripts/generate_gyp.py
	cd ../..

############

With sources above, you can now generate ffmpeg build targets with gyp:

	./tools/gyp/gyp -I build/common.gypi --depth=. ./third_party/ffmpeg/ffmpeg.gyp

Note: On Windows, GYP_DEFINES should also include clang=0 to disable clang.

############

Build ffmpeg with ninja:

	ninja -C out/Release ffmpeg

You will find build results in out/Release.

############

Generate new build files (to take GYP_DEFINES in account, and the ffmpeg modifications):

	gclient runhooks --force

############

Build custom NWjs:

	ninja -C out/Release nwjs

Note: this will take a *very* long time.

**Comment by vankasteelj** [comment]
Ok, so. Following the above steps to build nwjs entirely, there's a good and a bad news:

- The good news is that it compiles and reads HEVC \o/
- The bad news is that nw went from 120MB to 3.1GB (also \o/, in a weird way, that must be some kind of achievement)

**Comment by vankasteelj** [comment]
I was missing a build step. We now have a working build for linux64 \o/

**Comment by devlo** [comment]
@vankasteelj 

What about dts and dts-hd? Is it working ?

**Comment by vankasteelj** [comment]
building on any platform should be available following the same steps as above, I haven't tried because I was focusing on getting a build to work. I'll compile everything if we decide to use nw13 here, on Butter. 

As for dts and dts-hd, I can try with the linux build if you can provide a file using those. Theorically, it should work, the only impairement is with some AVI that are read (but bad, with fuzzyness and small jumps)

**Comment by G-Ray** [comment]
Thanks for your progress.
nw13 is needed to resolve issues on linux since an update of libnss3.
See https://github.com/popcorn-official/popcorn-desktop/issues/49

**Comment by vzamanillo** [comment]
@vankasteelj [Here](nwjs-ffmpeg-prebuilt) you can find an easy to use script for building ffmpeg (with and without proprietary codecs) based on your (great) previous work, the script can not do a custom builds for NW.js yet, We are considering adding this option.

I hope that will be useful for you.

**Comment by streger** [comment]
@vzamanillo Your link doesn't work.

**Comment by vzamanillo** [comment]
@streger, ops, bad c&p,sorry.

Thank you :).

**Comment by vankasteelj** [comment]
I'm afraid that without recompiling the correct flags for nwjs directly, it's going to lack ac3 and proper avi support. Maybe not. I'm not sure of anything. They already messed with my head when they switched to gn over gyp x)

**Comment by vzamanillo** [comment]
I am almost sure of that, but the script simplifies the ffmpeg compilation process, the next step will be a new script to automate the building NW.js procedure. Anyway, I will follow investigating at least to clarify myself about the build procedure and how should be more easy to do that.

I really would like not have to download 20gb to do a custom build for listening AC3 encoded audio, but is what we get... :/

**Comment by vankasteelj** [comment]
We're working internally to have a build, if we get results, i'll let you know.

**Comment by vankasteelj** [comment]
I'm trying this: 

```#!/bin/bash

#for linux64 atm. run : `script.sh nw18` for specific branch

if [ -z "$1" ]
  then
    MAIN="master"
else
    MAIN=$1
fi

echo "Building nwjs from sources, with ffmpeg patches [branch: $MAIN]"

# create main dir
mkdir -p nwjs-build
cd nwjs-build # nwjs-build

# get depot tool
git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
export PATH=`pwd`/depot_tools:"$PATH"

# get nwjs sources
mkdir -p nwjs
cd nwjs # nwjs-build/nwjs

# generate .gclient
gclient config --name=src https://github.com/nwjs/chromium.src.git@origin/$MAIN
rm .gclient
echo -e "solutions = [
  { \"name\"        : \"src\",
    \"url\"         : \"https://github.com/nwjs/chromium.src.git@origin/$MAIN\",
    \"deps_file\"   : \"DEPS\",
    \"managed\"     : True,
    \"custom_deps\" : {
        \"src/third_party/WebKit/LayoutTests\": None,
        \"src/chrome_frame/tools/test/reference_build/chrome\": None,
        \"src/chrome_frame/tools/test/reference_build/chrome_win\": None,
        \"src/chrome/tools/test/reference_build/chrome\": None,
        \"src/chrome/tools/test/reference_build/chrome_linux\": None,
        \"src/chrome/tools/test/reference_build/chrome_mac\": None,
        \"src/chrome/tools/test/reference_build/chrome_win\": None,
    },
    \"safesync_url\": \"\",
  },
]
cache_dir = None" > .gclient

# get repos
git clone https://github.com/nwjs/nw.js.git src/content/nw 
cd src/content/nw
git checkout $MAIN
cd ../../.. # nwjs-build/nwjs

git clone https://github.com/nwjs/node src/third_party/node
cd src/third_party/node
git checkout $MAIN
cd ../../.. # nwjs-build/nwjs

git clone https://github.com/nwjs/v8 src/v8
cd src/v8
git checkout $MAIN
cd ../.. # nwjs-build/nwjs

cd .. # nwjs-build

# get source code
gclient sync --with_branch_heads --no-hooks
./build/install-build-deps.sh
gclient runhooks

# build ninja conf
cd nwjs-build/nwjs/src
gn gen out/nw --args='is_debug=false is_component_ffmpeg=true target_cpu="x64" nwjs_sdk=true enable_nacl=true ffmpeg_branding="Chrome" proprietary_codecs=true enable_ac3_eac3_audio_demuxing=true enable_hevc_demuxing=true is_official_build=true enable_mse_mpeg2ts_stream_parser=true'

cd ../../.. # ./

# replace python build script lines

echo -e "--- build_ffmpeg.py	2016-10-18 19:45:18.883827200 +0200
+++ build_ffmpeg.py	2016-10-18 19:46:20.235113900 +0200
@@ -551,9 +551,9 @@
 
   # Google Chrome & ChromeOS specific configuration.
   configure_flags['Chrome'].extend([
-      '--enable-decoder=aac,h264,mp3',
-      '--enable-demuxer=aac,mp3,mov',
-      '--enable-parser=aac,h264,mpegaudio',
+      '--enable-decoder=aac,h264,mp3,eac3,ac3,hevc,mpeg4,mpegvideo,mp2,mp1,flac',
+      '--enable-demuxer=aac,mp3,mov,dtshd,dts,avi,mpegvideo,m4v,h264,vc1,flac',
+      '--enable-parser=aac,h264,mpegaudio,mpeg4video,mpegvideo,ac3,h261,vc1,h263,flac',
   ])
 
   # ChromiumOS specific configuration." > build_ffmpeg.patch

echo -e "--- ffmpeg_common.cc	2016-10-18 19:31:07.914680100 +0200
+++ ffmpeg_common.cc	2016-10-18 19:26:47.936317250 +0200
@@ -126,6 +126,10 @@
   switch (audio_codec) {
     case kCodecAAC:
       return AV_CODEC_ID_AAC;
+    case kCodecAC3:
+      return AV_CODEC_ID_AC3;
+    case kCodecEAC3:
+      return AV_CODEC_ID_EAC3;
     case kCodecALAC:
       return AV_CODEC_ID_ALAC;
     case kCodecMP3:" > ffmpeg_common.patch

patch -R nwjs-build/nwjs/src/third_party/ffmpeg/chromium/scripts/build_ffmpeg.py < build_ffmpeg.patch

# patch ffmpeg lib for ac3
patch -R nwjs-build/nwjs/src/media/ffmpeg/ffmpeg_common.cc < ffmpeg_common.patch

rm ffmpeg_common.patch build_ffmpeg.patch

cd nwjs-build/nwjs/src # nwjs-build/nwjs/src

# build ffmpeg
cd third_party/ffmpeg # nwjs-build/nwjs/src/third_party/ffmpeg
./chromium/scripts/build_ffmpeg.py linux x64 —branding=ChromeOS 

# trick nwjs into thinking it's chrome, not chromeos build (enables avi files)
rm -rf build.x64.linux/Chrome
mv build.x64.linux/ChromeOS build.x64.linux/Chrome

# copy ffmpeg conf
./chromium/scripts/copy_config.sh 

# generate gyp for ffmpeg build
./chromium/scripts/generate_gyp.py

cd ../.. # nwjs-build/nwjs/src

# generate ninja build files
GYP_CHROMIUM_NO_ACTION=0 ./build/gyp_chromium third_party/node/node.gyp

# build nwjs
ninja -C out/nw nwjs

# build node
ninja -C out/Release node

# copy node lib
ninja -C out/nw copy_node```

but tomorrow, right now it's sleep time

**Comment by vankasteelj** [comment]
So far, we have working codecs for hevc and ac3 (other are pretty easy to get), but still encountering issues with some avi files. 
Xvid simple works fine, but divx3 isn't recognized, and xvid packed stutters.

**Comment by streger** [comment]
Forget the .avi, there isn't even enough seeders for anything out there. DivX files are almost non-existent, and probably legally problematic. Think about future, not he past, most of the quality stuff will be re-encoded anyway.

**Comment by vzamanillo** [comment]
Your script looks pretty good, it's a great work, I am learning about the NW.js building procedure just right now. i'll let you know if we can simplify the build proccess.

**Comment by vankasteelj** [comment]
https://github.com/nwjs/nw.js/issues/5381

**Comment by thecyberd3m0n** [comment]
I'm trying to make the build but I've got some issues

> # generate gyp for ffmpeg build
> ./chromium/scripts/generate_gyp.py

but now generate_gyp.py is missing, I've got just generate_gn file

**Comment by thecyberd3m0n** [comment]
I've also facing the problem

> gyp: v8/src/v8.gyp not found (cwd: /home/tcdsoft/nwjs/src)
sounds like there are files missing on newer builds

**Comment by vzamanillo** [comment]
If you want to build a custom ffmpeg only without building NW.js try this

https://github.com/iteufel/nwjs-ffmpeg-prebuilt

**Comment by thecyberd3m0n** [comment]
Actually I need complete nwjs with ffmpeg, or another way for making node-webkit instance with all those formats working
