### ISSUE TITLE
./make_butter.sh isn't working properly

### ISSUE THREAD

**Issue by MRUBS** [butterproject/butter-desktop#341]
I have tried to all the steps and when i used this commant " ./make_butter.sh" and "grunt lang" on ubuntu 14.04 i get this,

![desctop screenshot](https://cloud.githubusercontent.com/assets/8060177/14202415/a0315422-f819-11e5-9f4a-a259f39ea0ff.png)

" grunt css" has no problem, 5 files created, 
" grunt nwjs " gives me nothing

not sure, i have search for that repository and it's gives me 404 error on github. Do, i need to make changes into this "make_butter.sh" file.

**Comment by vankasteelj** [comment]
Mmmmh, most probably. Let me check

**Comment by vankasteelj** [comment]
There you go :)

**Comment by MRUBS** [comment]
thanks, but what what should i do now from here, should i delete the ole repository and clone your git again and run the codes ?

**Comment by vankasteelj** [comment]
no need for that, you can just run:

```
cd butter-desktop
git pull
./make_butter.sh
```

git pull will sync your local code with upstream. You can redo 'git pull' every now and then (for example, every week) to see in-app the changes made here

**Comment by MRUBS** [comment]
great, thanks, i will try that and keep up to date.

**Comment by MRUBS** [comment]
that works, but here is a new problem, can you tell me what i'm missing with... I have tried to install butter project on Ubuntu 14.04 (AWS) and by following the codes that you referred works fine except "grunt start" command, i am sharing the screenshot of what i got.

![desctop screenshot](https://cloud.githubusercontent.com/assets/8060177/14225813/4046fc5e-f8f2-11e5-8ef1-1eda9e740940.png)

**Comment by vankasteelj** [comment]
you could `apt-get install libnotify-bin libnotify4` but somehow I doubt that will be enough. Isn't Ubuntu AWS an Ubuntu server, meaning without a Desktop Environment ? Because Butter uses NWJS (modified Chromium), and that requires a graphical interface. 

`grunt start` will start the program, like if you were to click the desktop icon of an installed program on Windows. Without graphical interface, I don't think you'll be able to start it, even less use it.

**Comment by MRUBS** [comment]
yes, you are right. AWS doesn't have desktop environment. So, i can't run
it on aws?

Can you tell me if that is possible or not, to make live streaming with
butter project in that AWS server.

On Sat, Apr 2, 2016 at 5:53 PM, Jean van Kasteel <notifications@github.com>
wrote:

> you could apt-get install libnotify-bin libnotify4 but somehow I doubt
> that will be enough. Isn't Ubuntu AWS an Ubuntu server, meaning without a
> Desktop Environment ? Because Butter uses NWJS (modified Chromium), and
> that requires a graphical interface.
>
> grunt start will start the program, like if you were to click the desktop
> icon of an installed program on Windows. Without graphical interface, I
> don't think you'll be able to start it, even less use it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/butterproject/butter-desktop/issues/341#issuecomment-204700294>
>



-- 
*M Rub Shuvo*

**Comment by MRUBS** [comment]
nope, it's not working. i think you are right about the graphical
interface. I am using windows 7. Is it possible to install on windows 7.

On Sat, Apr 2, 2016 at 8:13 PM, M Rub Shuvo <m.rub.shuvo@gmail.com> wrote:

> yes, you are right. AWS doesn't have desktop environment. So, i can't run
> it on aws?
>
> Can you tell me if that is possible or not, to make live streaming with
> butter project in that AWS server.
>
> On Sat, Apr 2, 2016 at 5:53 PM, Jean van Kasteel <notifications@github.com
> > wrote:
>
>> you could apt-get install libnotify-bin libnotify4 but somehow I doubt
>> that will be enough. Isn't Ubuntu AWS an Ubuntu server, meaning without a
>> Desktop Environment ? Because Butter uses NWJS (modified Chromium), and
>> that requires a graphical interface.
>>
>> grunt start will start the program, like if you were to click the
>> desktop icon of an installed program on Windows. Without graphical
>> interface, I don't think you'll be able to start it, even less use it.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/butterproject/butter-desktop/issues/341#issuecomment-204700294>
>>
>
>
>
> --
> *M Rub Shuvo*
>



-- 
*M Rub Shuvo*

**Comment by MRUBS** [comment]
let me try with VNC server, see if i can get GUI on AWS. btw thanks a lot
for your help.

On Sat, Apr 2, 2016 at 8:28 PM, M Rub Shuvo <m.rub.shuvo@gmail.com> wrote:

> nope, it's not working. i think you are right about the graphical
> interface. I am using windows 7. Is it possible to install on windows 7.
>
> On Sat, Apr 2, 2016 at 8:13 PM, M Rub Shuvo <m.rub.shuvo@gmail.com> wrote:
>
>> yes, you are right. AWS doesn't have desktop environment. So, i can't run
>> it on aws?
>>
>> Can you tell me if that is possible or not, to make live streaming with
>> butter project in that AWS server.
>>
>> On Sat, Apr 2, 2016 at 5:53 PM, Jean van Kasteel <
>> notifications@github.com> wrote:
>>
>>> you could apt-get install libnotify-bin libnotify4 but somehow I doubt
>>> that will be enough. Isn't Ubuntu AWS an Ubuntu server, meaning without a
>>> Desktop Environment ? Because Butter uses NWJS (modified Chromium), and
>>> that requires a graphical interface.
>>>
>>> grunt start will start the program, like if you were to click the
>>> desktop icon of an installed program on Windows. Without graphical
>>> interface, I don't think you'll be able to start it, even less use it.
>>>
>>> —
>>> You are receiving this because you authored the thread.
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/butterproject/butter-desktop/issues/341#issuecomment-204700294>
>>>
>>
>>
>>
>> --
>> *M Rub Shuvo*
>>
>
>
>
> --
> *M Rub Shuvo*
>



-- 
*M Rub Shuvo*

**Comment by vankasteelj** [comment]
you can install it on windows 7, the documentation doesn't states every requirement, i'll make sure to update that. see https://github.com/butterproject/butter-desktop/issues/343

**Comment by MRUBS** [comment]
hi Jean, i solved the problem, i used AWS GUI and grunt start just worked
great.

On Sat, Apr 2, 2016 at 8:54 PM, Jean van Kasteel <notifications@github.com>
wrote:

> you can install it on windows 7, the documentation doesn't states every
> requirement, i'll make sure to update that. see #343
> <https://github.com/butterproject/butter-desktop/issues/343>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/butterproject/butter-desktop/issues/341#issuecomment-204728972>
>



-- 
*M Rub Shuvo*
