### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by vankasteelj** [butterproject/butter-desktop#343]
- Contributing
 - [ ] Report bugs
 - [ ] Suggest enhancements
 - [ ] Submit PR
 - [ ] Translate
 - [ ] Contributor license agreement
 - [ ] links to code standards/git workflow/building-working
- Github
 - [x] Issue template
 - [x] PR template
- Code standards
 - [x] Javascript
 - [ ] HTML
 - [ ] CSS
 - [x] providers
 - [ ] streamers
- Git workflow
 - [x] Commit messages
 - [x] Clean up history
 - [x] Tests
- Building/Working on butter
 - [x] compatible platforms
 - [x] requirements (node, npm, git)
 - [x] instructions platform-specific (if needed)
 - [x] what commands?
 - [x] video tutorial (for windows users, not used to source code things)

see `docs/rewrite` branch

**Comment by vankasteelj** [comment]
# Compatible platforms:

Windows: 
- 7, 8, 8.1, 10 (all flavors, x86 only (ie: no arm, also known as mobile), 32bits or 64bits)
- what about vista?

Linux:
- Ubuntu >= 14.04 (what about 12.04? it might work with the LD_LIBRARY_PATH)
- Mint/Debian/Elementary?
- Fedora?
- Arch?
- Suse?
- CentOS?

OSX:
- >= 10.9, only 64bits ?!? I don't know at all

**Comment by vankasteelj** [comment]
# Requirements 

- NodeJS - https://nodejs.org
-

**Comment by vankasteelj** [comment]
# Platform-specific instructions

**Comment by vankasteelj** [comment]
>  Butter Project trello board

Link should be added somewhere.

**Comment by vankasteelj** [comment]
JS code standards:

Should we indicate things like: 
"if you need to loop, prefer `for (var i = 0, len = arr.length; i < len; i++) {}` over other loops, like `for (var i in arr)` or `arr.forEach()`" ?

**Comment by xaiki** [comment]
we prefer `arr.forEach()` and `_.map()`

**Comment by vankasteelj** [comment]
forEach is much slower, 100ms slower on 10.000 iterations, going exponentially slower as the iterations go up

**Comment by xaiki** [comment]
but is much clearer to read, don''t need to optimize unless it's a hotpath.
