### ISSUE TITLE
wcjs (webchimera)

### ISSUE THREAD

**Issue by vankasteelj** [butterproject/butter-desktop#344]
- [x]  player.js base functions
- [x] database/trakt
- [ ] display network info
- [ ] close button
- [x] keyboard/mouse shortcuts
- [ ] metadata check
- [ ] playnext (playlist)
- [ ] styl wcjs-player
- [ ] subtitles
- [ ] youtube
- [ ] build process

see branch _test/wcjs_

wcjs-player uses webchimera.js, which uses VLC library instead of HTML api. It allows to play all VLC-supported codecs and formats.

Note: we can then switch to nw13 easely

**Comment by amilajack** [comment]
From my experience, WebChimera causes insanely high CPU usage. Checkout my [Release 0.0.3 alpha](https://github.com/amilajack/popcorn-time-desktop/tree/release-0.0.3-alpha) branch and try playing a tv show, which is going to fallback to WebChimera

**Comment by vankasteelj** [comment]
wcjs will be dropped soon, vlclib > 2 has too many breaking changes
