### ISSUE TITLE
gulp

### ISSUE THREAD

**Issue by vankasteelj** [butterproject/butter-desktop#347]
- [x] set gulp
- [x] task run
- [x] task build
- [x] task dist
- [x] task compress: currently working in tgz, but compression ratio is bad, see if tgz can be tweaked or use txz.
- [x] task makensis
- [ ] task bower_clean
- [x] task debian package
- [x] task codesign: I'm not sure we have a dev signature for osx
- [ ] task create dmg: dmg or .app.tgz?
- [ ] task setexecutable: I think it isn't necessary. I might be wrong.
- [x] task clean
- [x] task jshint
- [x] task jsbeautifier
- [x] githooks precommit

note: it doesnt seem possible to build rpm with `fakeroot alien -r --scripts mypackage.deb` as I can't see any scripts. Someone using redhat-like distribution will have to test.

**Comment by vankasteelj** [comment]
@xaiki with gulp being ES6, I think we need to upgrade package.json requirements from "node >= 0.12" to "node >= 4"

**Comment by xaiki** [comment]
@vankasteelj yes, tottally.

**Comment by vankasteelj** [comment]
I think we should dump old node.
