### ISSUE TITLE
Set WM_CLASS

### ISSUE THREAD

**Issue by rightaway** [butterproject/butter-desktop#356]
On Linux the WM_CLASS(STRING) property isn't set (when running `xprop`), which would allow window managers to do things like put it in the right workspace, etc.

**Comment by vankasteelj** [comment]
Wouldn't that be more suited on NWjs repo?

**Comment by vankasteelj** [comment]
I don't think there's anything we can do, I'll just link there: https://github.com/nwjs/nw.js/issues/3266 and close this. Please reopen if you have a solution working from our side
