### ISSUE TITLE
githooks

### ISSUE THREAD

**Issue by vankasteelj** [butterproject/butter-desktop#367]
githooks are a way to set specific tasks before git does something. We currently use the `pre-commit` hook, that allows to add some tasks before committing is possible. This is what how it works and what it does:

- `git add -A`: git default, adds the modified files to the list of files to commit
- `git commit`:
     - `pre-commit`: git-guppy (gulp) injected task
         - `jshint`: gulp task, checks the linting of the project, prevents committing if linting fails
     - `commit`: git default, commits

There's the possibility of making `commit` fail if code isn't beautified (wrong indent is an example of non-beautified code). Should it behave like that?

**Comment by ZakariaRidouh** [comment]
I think it should check for the bare minimum when commiting such as a quick few second formating check that checks if the code follows the Butter JS standards.
