### ISSUE TITLE
Grunt sortby.year

### ISSUE THREAD

**Issue by mattgilman10** [butterproject/butter-desktop#386]
Using the grunt build system (incase you guys ever switch back, or this may still be an issue with the gulp build system), the sort by year function does not work whatsoever. It changes the movie order from the original, but it does not change it to sort by year at all. Not sure how it is sorting it.

Environment:
Mac OS X

Technical:
Version: 41.0.2272.76
Downloaded from source code on github

**Comment by vankasteelj** [comment]
grunt (or gulp, now) has nothing to do with the app, it's parabuild only

**Comment by mattgilman10** [comment]
Just for clarification purposes, what do you mean by parabuild? Just curious

Not sure if I explained the issue correctly. The issue is with the sort function which may not be effected at all by the build systems. Not sure what file I can find that in, in order to fix the functionality of the sort method, in regards to sorting movies by a specific type.

**Comment by vankasteelj** [comment]
parabuild is what is "around the build". grunt and gulp are only tools allowing to use modules in order to build. but ok, your precision works
