### ISSUE TITLE
Unable to grunt start due to ES6 issues

### ISSUE THREAD

**Issue by sidazhang** [butterproject/butter-desktop#391]
Operating System Version:
OS X 10.11.4

Node Version:
v0.10.32

NPM Version:
2.8.2

Popcorn Time Version:
Latest development build: 4f15b03b21411c86446e606d5e096310b8511e2a

Download date:
May 7th, 2016

#### Steps to repoduce the behaviour
- Install by running `./make_popcorn.sh`
- grunt start
- You should see an issue with package which uses ES6

```
Running "exec:osx32" (exec) task
>> [79650:0507/164047:ERROR:nw_shell.cc(335)] /Users/sidazhang/scripts/popcorn-desktop/node_modules/peerflix/node_modules/torrent-stream/node_modules/fs-chunk-store/node_modules/path-exists/index.js:4
>> module.exports = fp => new Promise(resolve => {
>>                     ^^
>> SyntaxError: Unexpected token =>
>>     at exports.runInThisContext (vm.js:53:16)
>>     at Module._compile (module.js:434:25)
>>     at Object.Module._extensions..js (module.js:469:10)
>>     at Module.load (module.js:346:32)
>>     at Function.Module._load (module.js:301:12)
>>     at Module.require (module.js:356:17)
>>     at require (module.js:375:17)
>>     at Object.<anonymous> (/Users/sidazhang/scripts/popcorn-desktop/node_modules/peerflix/node_modules/torrent-stream/node_modules/fs-chunk-store/index.js:8:18)
>>     at Module._compile (module.js:451:26)
>>     at Object.Module._extensions..js (module.js:469:10)
>> [79650:0507/164047:INFO:CONSOLE(4)] "Uncaught SyntaxError: /Users/sidazhang/scripts/popcorn-desktop/node_modules/peerflix/node_modules/torrent-stream/node_modules/fs-chunk-store/node_modules/path-exists/index.js:4
>> module.exports = fp => new Promise(resolve => {
>>                     ^^
>> Unexpected token =>", source: /Users/sidazhang/scripts/popcorn-desktop/node_modules/peerflix/node_modules/torrent-stream/node_modules/fs-chunk-store/node_modules/path-exists/index.js (4)
>> [79650:0507/164047:INFO:CONSOLE(6)] ""Database path: /Users/sidazhang/Library/Application Support/Popcorn-Time"", source: app://host/src/app/database.js (6)
```

#### Workaround:
By adding `js-flags` to `package.json`
`  "js-flags": "--harmony --harmony_arrow_functions",`

**Comment by sidazhang** [comment]
@VitorVRS @vankasteelj It seems like that this dependency was recently updated to use arrow functions a few days ago.

https://github.com/sindresorhus/path-exists/commit/0a210abfde711e0faae3f518d815ef69029148c5

**Comment by vankasteelj** [comment]
we use gulp and node 0.12 is the minimal version, 4.x or above recommended, you'll have to upgrade

**Comment by sidazhang** [comment]
@vankasteelj Could you please update the CONTRIBUTING.md. The wiki refers to minimal version to be v0.10.*

https://github.com/butterproject/butter-desktop/blob/master/CONTRIBUTING.md

**Comment by vankasteelj** [comment]
https://github.com/butterproject/butter-desktop/issues/343
