### ISSUE TITLE
SSL_ERROR_ENCRYPTION_FAILURE

### ISSUE THREAD

**Issue by d33pcode** [butterproject/butter-desktop#394]
Downloaded the 64bit (Linux) beta 3.9 currently online on popcorntime.sh .
I noticed i couldn't view images for "film" and "series" sections; opening Popcorn-Time via terminal shows the following line when I click on one of them:
`[5889:0513/214251:WARNING:nss_ssl_util.cc(374)] Unknown SSL error -12218 (SSL_ERROR_ENCRYPTION_FAILURE) mapped to net::ERR_SSL_PROTOCOL_ERROR`

**Comment by xaiki** [comment]
hey there, this is butter project not popcorn time, report to them the issue you have with their software.
