### ISSUE TITLE
Removing Grunt

### ISSUE THREAD

**Issue by metteemo** [butterproject/butter-desktop#402]
Low priority: there's still some mentions of Grunt in the repo, removing them would be a good idea

https://github.com/butterproject/butter-desktop/search?utf8=%E2%9C%93&q=grunt

**Comment by vankasteelj** [comment]
https://github.com/butterproject/butter-desktop/blob/c85b19856af20256b71eb7e6f42dc31c9baaed92/gulpfile.js#L203 this one is really funny :p old habits die hard. for the "docs" (.md), don't change anything now, there's a branch for updated doc, but on the other files, you can PR if you want (or anyone actually)
