### ISSUE TITLE
Looking for contributors for Electron fork

### ISSUE THREAD

**Issue by amilajack** [butterproject/butter-desktop#410]
I am working on a new version of the popcorn-desktop client with the goal of it being merged into this repository.

The project is build from scratch and features **ES6, React, Webpack, Electron**, and other new technologies:

[https://github.com/amilajack/popcorn-desktop-experimental](https://github.com/amilajack/popcorn-desktop-experimental)

It also has significant performance improvements over all the current clients. However, the project is very early stage and needs work!

Let me know if you are interested in contributing!

**Comment by tehp** [comment]
I am willing to contribute. 

Would it be possible to move the repo to the official org?

**Comment by amilajack** [comment]
I would recommend we do that after it gets out of an experimental stage. Right now, there is already an experimental client in the official org. Maybe we should wait until it is feature-par with the other experimental client. What do you say?

**Comment by tehp** [comment]
Works for me. Let's see if we get many more contributors then we can discuss communication.

**Comment by xaiki** [comment]
thanks for your effort !

once you get design par and can integrate butter-providers, we can start to integrate it.
you will to change the name too.

**Comment by amilajack** [comment]
@xaiki yup, definitely! I will be working on a provider that can wrap the existing popcorn time providers. Also are you able to contribute?

**Comment by amilajack** [comment]
@tehp  sorry for late response. just made a gitter for the project:

https://gitter.im/amilajack/popcorn-desktop-experimental

There, we can discuss the todos of the project:
https://github.com/amilajack/popcorn-desktop-experimental/wiki/Road-Map

**Comment by amilajack** [comment]
@tehp here's a list of what we've completed: https://github.com/amilajack/popcorn-time-desktop/wiki/Road-Map-and-Progress. Are you interested in helping out with subtitle support or support external playback methods (vlc player, dlna, chromecast, airplay)?

**Comment by xaiki** [comment]
how are butter providers in your codebase ? how about renaming it to `butter-` namespace ?

**Comment by amilajack** [comment]
@xaiki The providers are in the following directory:

https://github.com/amilajack/popcorn-time-desktop/tree/master/app/api/torrents

The [Torrent.js](https://github.com/amilajack/popcorn-time-desktop/blob/master/app/api/Torrent.js) is responsible for merging the results together

**Comment by ZakariaRidouh** [comment]
I think allowing any type of namespace to be used would be optimal.

**Comment by xaiki** [comment]
@amilajack we have a definition for butter providers: https://github.com/butterproviders/butter-provider, if those wouldn't work for you we can have a chat about it, but that would be a *must* *have* to move to the `butter-` namespace.

**Comment by xaiki** [comment]
@amilajack write me a an email at x@btn.sh so i can invite you to slack, cheers

**Comment by amilajack** [comment]
We just released **[0.0.5](https://github.com/amilajack/popcorn-time-desktop/releases/tag/v0.0.5-alpha)**. Now onto **[0.0.6](https://github.com/amilajack/popcorn-time-desktop/wiki/Road-Map-and-Progress#release-006-alpha-ui-redesignmvp)**, which will be a UI overhaul of the presentation layer of the application. Anyone with front-end/react/redux is welcome to contribute!

**Comment by VitorVRS** [comment]
@amilajack UI will be the same interface as Butter/PCT ?
