### ISSUE TITLE
Streaming via DLNA not working

### ISSUE THREAD

**Issue by dyaniv** [butterproject/butter-desktop#413]
Trying to stream via DLNA doesn't work, the screen shows downloading and progress, but the cast to the smart TV (Samsung) doesn't happen.

**Comment by xaiki** [comment]
TV model,
Butter Version
Build Date.

**Comment by xaiki** [comment]
TV model,
Butter Version
Build Date.

**Comment by dyaniv** [comment]
TV Model: H6400
Butter Version: 0.3.8-5a
Build Date: 3 days ago

**Comment by vankasteelj** [comment]
PR/dlna_chromecast might help with samsung, but it breaks LG compatibility. I heard from jaruba not so long ago, apparently he cracked dlna, but I'm not sure he open-sourced it.

**Comment by liorbp** [comment]
Same here. DLNA is broken with LG WebOS... The TV is not detected at all on Popcorn Time v0.3.9 build #135

**Comment by vankasteelj** [comment]
Exactly what I said.

**Comment by streger** [comment]
Are there some other open source DLNA implementations that we could look into than those two?
There was issue on nodecast-js about this and got resolved long time ago, what happened?
https://github.com/gyzerok/nodecast-js/issues/5
