### ISSUE TITLE
unable to build/install ubuntu 16.04

### ISSUE THREAD

**Issue by Goddard** [butterproject/butter-desktop#429]
basically just can't build on ubuntu 16.04 any help is appreciated

install log
http://pastebin.com/XfzmuddG

**Comment by amilajack** [comment]
Try this on the latest npm and node versions:

```
npm cache clean
rm -rf node_modules
npm i
```

and build again

**Comment by Goddard** [comment]
no luck

**Comment by amilajack** [comment]
Try this:
https://github.com/chentsulin/electron-react-boilerplate/issues/346#issuecomment-241379306

**Comment by vankasteelj** [comment]
I have 16.04 installed on my machine, but it's an upgrade from 15.x, I know some deps aren't the same with this particular ubuntu version if you installed from scratch or if you upgraded, can you tell me if you still have issue and if you upgraded or installed new ?

**Comment by Goddard** [comment]
Yeah it still isn't working for me.

I did a fresh install of Kubuntu 16.04, but repos are same as Ubuntu.

**Comment by vankasteelj** [comment]
Try:

    node -v
    nodejs -v
    npm -v

**Comment by Goddard** [comment]
$ node -v
v4.2.6
$ nodejs -v
v4.2.6
$ npm -v
3.5.2

**Comment by vankasteelj** [comment]
Mmh. What if you edit those 2 files :

1) Remove `"guppy-pre-commit": "^0.3.0",` from `package.json`

2) Remove `gulp.task('pre-commit', ['jshint']);` from `gulpfile.js` (l.422)

**Comment by vankasteelj** [comment]
Any update ?

**Comment by BartWillems** [comment]
Same problem here

**Comment by vankasteelj** [comment]
And did you try the above?

**Comment by delysh** [comment]
Hi,
I've tried everything above, still can't get successful build.
When running `gulp build` getting this:
```
.....
[16:47:49] Finished 'css' after 11 s
[16:47:49] Starting 'nwjs'...
Received status code 400: https://raw.githubusercontent.com/butterproject/nwjs-prebuilt/master/
......
```

And then, when trying `gulp run` getting error:
```
Running linux64 from cache
linux64 is not available in cache. Try running `gulp build` beforehand
[16:49:28] 'run' errored after 17 ms
[16:49:28] Error: spawn cache/0.12.2/linux64/nw ENOENT
    at exports._errnoException (util.js:1036:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
Butter exited with code -2
```
Any suggestions?

**Comment by vankasteelj** [comment]
Please `npm update` then `gulp build` again :)

**Comment by delysh** [comment]
Nope. Still no success :(
Now i'm getting:
```
[20:24:30] Starting 'nwjs'...
{ Error: Command failed: npm ls --production=true --parseable=true
npm ERR! invalid: node-webkit-fdialogs@0.2.7 /home/.../butter-desktop/node_modules/node-webkit-fdialogs

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm ls --production=true --parseable=true' }
```
Any other suggestions? :)

nodejs -v
v6.7.0
npm -v
3.10.5

**Comment by vankasteelj** [comment]
You could try replacing "latest" by "0.2.7" in package.json

    cd node_modules && rm -rf node-webkit-fdialogs
    npm install && gulp build

**Comment by vankasteelj** [comment]
Note that:

```
cd ~
git clone https://github.com/butterproject/butter-desktop.git
cd butter-desktop
sudo npm install -g gulp-cli bower
npm install
gulp build
gulp run
```

Works fine on Ubuntu 16.04. You're probably doing something wrong.

**Comment by delysh** [comment]
Replacing "latest" with "0.2.7" in the package.json helped. After cleaning npm cache and running `npm update`, `gulp build` was successful.
Thanks a lot! :-)

**Comment by eaterjolly** [comment]
```
> guppy pre-commit

/usr/bin/env: ‘node’: No such file or directory

```
Was in my npm update log while following these steps. For more context:
```
 sudo npm install

> guppy-pre-commit@0.4.0 postinstall /home/john/Engines/peer-to-peer/Hierarchal-Data/Cultural-Film/butter-desktop/node_modules/guppy-pre-commit
> guppy pre-commit

/usr/bin/env: ‘node’: No such file or directory
npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
```

**Comment by BadPractice** [comment]
still having the same issue

**Comment by immartian** [comment]
same here, 

```
popcorn-desktop$ gulp run
[19:08:16] Using gulpfile ~/lab/p2p/popcorn-desktop/gulpfile.js
[19:08:16] Starting 'run'...
Running linux64 from cache
linux64 is not available in cache. Try running `gulp build` beforehand
[19:08:16] 'run' errored after 20 ms
[19:08:16] Error: spawn cache/0.44.5-sdk/linux64/nw ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by orekav** [comment]
Same issue with my Raspberry Pi 3B
Buster 32 bits

Error: spawn cache/0.44.5-sdk/linux32/nw ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by vankasteelj** [comment]
RaspberryPi is built with ARM, not x86. NWjs doesn't support ARM officially, you'll have to manually tinker with some unofficial binaries if you want to try to use anything on it (spoiler: the RPi 4 is not powerfull enough for NWjs smooth rendering, I doubt the 3 will be even usable)
