### ISSUE TITLE
[Feature] File Selector Playlist Support

### ISSUE THREAD

**Issue by anassahmed** [butterproject/butter-desktop#440]
### Description

I don't know if someone already requested that before, but I think some torrents (the complete season of specific show torrents) which includes multiple video files can be added as a playlist as you're already downloading the whole torrent (as far as I have noticed).

Downloading the videos should continue even the current one had been completed and seeding for all videos should also continue to benefit all peers not only the current one.

If you think this is a good idea, I hope you consider it. I do know JS, but I don't know any NodeJS, so I couldn't do it myself. Maybe I can do it after learning some Node. :smile:

**Comment by xaiki** [comment]
this is needed to support some anime-kind torrents, but not our focus for now. probably pending @VitorVRS 's webtorrent work and the plan to split streamers.

**Comment by vankasteelj** [comment]
see #570
