### ISSUE TITLE
Failed to run after build as well as warning while building (Linux)

### ISSUE THREAD

**Issue by gameslayer** [butterproject/butter-desktop#474]
here is the full log on paste bin

[Pastebin Link](http://pastebin.com/c5S8hKGR)

**Comment by vankasteelj** [comment]
Seems like bower didn't run. Try `npm install` again, check that you have backbone folders in src/app/vendor

**Comment by gameslayer** [comment]
You do sudo npm install as it wont work without permission to run, sudo npm install and gulp build ran fine but I still have the same error trying to run it. I see videojsplugins.js and videojshooks.js in src/app/vendor and I haven't made any changes to the file which I got directly from this github page.

**Comment by vankasteelj** [comment]
Ok, that might be why.

Erase everything (`rm -rf butter-desktop`), then do:

    `sudo npm install -g gulp-cli`

then without sudo:

    `npm install`
