### ISSUE TITLE
What codecs are supported?

### ISSUE THREAD

**Issue by jakop345** [butterproject/butter-desktop#499]
What codecs are supported?

**Comment by vzamanillo** [comment]
Supported decoders:

Linux and Mac
- `aac,ac3,aac3,h264,mp1,mp2,mp3,mpeg4,mpegvideo,msmpeg4v1,msmpeg4v2,msmpeg4v3,hevc,flv,dca,flac`

Windows

- `aac,ac3,eac3,h264,mp1,mp2,mp3,mpeg4,mpegvideo,hevc,flv,dca,flac`

**Comment by xaiki** [comment]
@vzamanillo care to close this with a PR appending to readme ?

**Comment by vankasteelj** [comment]
for nw18 it is, maybe there will be some way in the future to include broader codecs
