### ISSUE TITLE
play-now button css wrong

### ISSUE THREAD

**Issue by vankasteelj** [butterproject/butter-desktop#534]
The player chooser is all messed up

**Comment by xaiki** [comment]
![screenshot from 2016-12-10 19-35-09](https://cloud.githubusercontent.com/assets/127133/21076653/ce3a73a4-bf0f-11e6-8565-5a3bebe3c653.png)
looks good here ?

**Comment by vankasteelj** [comment]
on fileselector too?

**Comment by xaiki** [comment]
`    <div class="button dropup" id="player-chooser2"></div>`
ah i missed that ... removing the button class should fix it, player-chooser handles it's own styling now.
