### ISSUE TITLE
Popcorn time managed to snif me while browsing

### ISSUE THREAD

**Issue by alkelani1** [butterproject/butter-desktop#542]
### Description

I use popcorn-time 0.3.10-Linux-64 edition, usually I start the program from cli,
I was surprised to see what I was browsing in Firefox in popcorn time log.
I think butter is now built based on firefox, but I am not sure of that,
but I am sure of that I saw what I was browsing in the logs.

### Steps to Reproduce

Unfortunately I could not reproduce the issue, therefore I have no steps.

**Expected behavior:** 
No sniffing
**Actual behavior:** 
Butter is sniffing 
### Technical details
 Linux ubuntu 16.04
popcorn-time 0.3.10-Linux-64 edition
Firefox 50.1.0

**Comment by vankasteelj** [comment]
1) we are not popcorn time, nor responsible for what they do.
2) nwjs is the browser, it's a merge between chromium and nodejs, so no : it isn't firefox
3) there is no code to "sniff" anything on your computer. Butter accesses to: 
- Windows registry (on install & uninstall only)
- Files & Folders (%temp% for bittorrent pieces and %localappdata% for databases, and drives for external players)
- Process list : to kill himself & spawn back on F11 key
- Local network : for dlna/airplay/chromecast

4) The only contact there is between the application and the web are: 
- Bittorrent network & the defined trackers on each torrent
- The defined APIs by the distributor
- The update endpoint (on start) that is checked. Eventually the update executable, defined on the update endpoint json (in the future, it'll be the bittorrent network too)
- Trakt
- Tvdb, omdb, fanart, tmdb

5) Absolutely no data is sent from the app TO the web, at the exception of Trakt, if you're logged in.

6) The only time the app writes something to the local network is for video streaming, and it uses localhost only.

**Comment by xaiki** [comment]
you probably opened firefox and popcorntime with the same terminal.

**Comment by alkelani1** [comment]
@vankasteelj Thanks for explanation.
@xaiki I am sure I did not.
Thanks again.
