### ISSUE TITLE
Movie details sets list into "loading mode" for too long

### ISSUE THREAD

**Issue by vankasteelj** [butterproject/butter-desktop#546]
- [x] Movie details are loaded immediately but the list goes on "loading" mode, if you close details you're stuck for a few seconds by the spinner
- [x] Provider-archive sends back errors (`TypeError: Cannot read property 'length' of undefined` - butter-provider-archive\index.js:123:39)
- [x] Movie details are broken because no torrents exist for archive

I'm sure the list goes on

**Comment by xaiki** [comment]
fixed 2, and probably 3. with latest push to archive.

**Comment by xaiki** [comment]
can't really figure out 1 though ...

**Comment by vankasteelj** [comment]
seems fixed by your commits
