### ISSUE TITLE
play now button misplaced

### ISSUE THREAD

**Issue by vankasteelj** [butterproject/butter-desktop#555]
There isnt enough space: 

movie_details
![nw_2016-12-04_11-33-50](https://cloud.githubusercontent.com/assets/12599850/20865528/7452aeb4-ba15-11e6-8a2e-69d813c6aedb.png)

show_detail:
![nw_2016-12-20_10-34-32](https://cloud.githubusercontent.com/assets/12599850/21345312/0cf605bc-c6a0-11e6-8786-b1d9552cd043.png)

**Comment by vankasteelj** [comment]
Bonus: 
![nw_2016-12-20_10-37-23](https://cloud.githubusercontent.com/assets/12599850/21345371/4bdddd18-c6a0-11e6-8cc2-1cb03d6832cf.png)

**Comment by xaiki** [comment]
haha, the bug is in FRENCH !!! ;) ok, we need a proper fix for this... but as @abad and @btzr-io are redesigning those views i wonder how much effort we should put into it now.

**Comment by SrPatinhas** [comment]
@vankasteelj @xaiki that is not a big deal, just need to change the size of the number container

**Comment by xaiki** [comment]
not sure if this is fixed, but it's pending redesign.
