### ISSUE TITLE
Support Flatpak (for Linux)

### ISSUE THREAD

**Issue by xaiki** [butterproject/butter-desktop#559]
See
https://flatpak.org

https://github.com/endlessm/snap4arduino-flatpak
https://github.com/Microsoft/vscode/pull/16169

**Comment by lil5** [comment]
#652 doesn't have an explained conclusion: is there Flatpack functionality now or is it still in development (if so shouldn't the issue reopen)?

An explanation should help those trying to create a Flatpack (if there is please link it).

**Comment by xaiki** [comment]
hello,
the master branch of butter-desktop allows you to create a flatpak, that is it's for pretty old code.
the dev branch currently does not create a flatpak, but it's pretty easy for anyone to modify the electron-builder config to make one.

patches are welcome
