### ISSUE TITLE
Fails on this: bower install --config.interactive=false

### ISSUE THREAD

**Issue by kemosabe73** [butterproject/butter-desktop#601]
### Description
My npm install fails on windows 7, I have downloaded the latest butter version yesterday(Feb 4, 2017).

### Steps to Reproduce

1. After typing npm install on my command prompt the following appears:

bower backbone#1.0.0 - 1.3.x        EAI_AGAIN Request to https://bower.herokuapp.com/packages/backbone failed: getaddrinfo EAI_AGAIN bower.herokuapp.com:443

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! Butter@0.3.8-5a postinstall: `bower install --config.interactive=false`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Butter@0.3.8-5a postinstall script 'bower install --config.interactive=false'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Butter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install --config.interactive=false
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Butter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Butter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\sonyvaiopc\Downloads\butter-desktop-master\npm-debug.log

**Comment by xaiki** [comment]
looks like a transient failure, please try again.
