### ISSUE TITLE
Windows 10 nothing opens

### ISSUE THREAD

**Issue by geoariton** [butterproject/butter-desktop#619]
### Description

Well, I've installed everything on Windows 10 Anniversary edition, got to the last step "gulp run" and... nothing happens, i see 4 nwjs.exe projects in task manager, but nothing opens up.

### Steps to Reproduce

1. Install according to instructions on Windows 10
2. run "gulp run"

**Expected behavior:** 
Something to happen, shouldn't a GUI open up?

**Actual behavior:** 
Nothing happens, just 4 processes who consume a bit of ram (~50mb)
Also, after gulp run, i have this:
[21:37:12] Using gulpfile D:\Projects\Node\Butter\gulpfile.js
(node:4932) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[21:37:12] Starting 'run'...
Running win32 from cache

### Technical details
 
- OS: Windows 10 PRO 1607
- Can't see which version of Butter i'm supposed to be running...

**Comment by vankasteelj** [comment]
you should see an UI indeed. Note that on first run, depending on your computer, it could take up to 1min to open nwjs, but not more than that. You can also try directly `./cache/0.18.6-sdk/win32/nw.exe .`

**Comment by geoariton** [comment]
If i try that, it opens a window with just

nw.js v0.18.6
Node v7.1.0
Chromium 54.0.2840.99
commit hash: 3ca3c5b-808f8b7-90170c3-86dc1eb

**Comment by vankasteelj** [comment]
you're missing the final dot

**Comment by geoariton** [comment]
Oh, apparently it's the same thing. 4 processes, no GUI

**Comment by vankasteelj** [comment]
then you're missing something :

    rm -rf node_modules src\app\vendor
    npm install
    gulp css
    gulp run

**Comment by geoariton** [comment]
DAMN, thank you!

The first gulp run gave me some errors, but i tried again and now i have the full GUI. I guess i was missing some files.

Thanks again!
