### ISSUE TITLE
Error loading subtitle and subtitle list empty

### ISSUE THREAD

**Issue by desyncr** [butterproject/butter-desktop#620]
### Description

Error loading subtitle and subtitle list empty when loading a torrent partially or fully fetched/downloaded.

### Steps to Reproduce

1. Load any title
  1.1 Default subtitle, if configured, should be loaded
  1.2 Subtitle list should be populated
2. Close currently playing title
3. Load same title

**Expected behavior:** Subtitle list should be populated in both cases

**Actual behavior:** Subtitle list is empty

### Technical details
 
- Fedora 23
- Butter v3.10
- Console logs: https://gist.github.com/desyncr/66c0b84a1574065acff13707a5a6f536

**Comment by vankasteelj** [comment]
I see "38 subtitles found" in your logs

**Comment by desyncr** [comment]
Yep, I saw it too. I know there are subtitles available, the issue is the select is not populated with them.

**Comment by vankasteelj** [comment]
I'll have to check, is this new from today or did you only try it today ?

**Comment by desyncr** [comment]
It happened to me multiple times.

**Comment by vankasteelj** [comment]
Wait a sec. You're not using butter ! We removed these logs more than 3 months ago and we're at 3.8.5

**Comment by desyncr** [comment]
mmm damn clones. Sorry for the inconvenience.
