### ISSUE TITLE
gulp build fails to download NWjs from builds.butterproject.org

### ISSUE THREAD

**Issue by kwill** [butterproject/butter-desktop#624]
### Description

When I try to `gulp build` on Ubuntu 16.10, I get an error (below).

### Steps to Reproduce

1. `sudo npm install -g gulp-cli` (required for -g on Ubuntu)
2. `npm install` (this works)
3. `gulp build`

**Expected behavior:** Builds butter-desktop ready for a `gulp run`

**Actual behavior:**

```
desktop> gulp build
[17:53:55] Using gulpfile /mnt/Big/Data/Apps/butter-desktop/gulpfile.js
[17:53:55] Starting 'build'...
[17:53:55] Starting 'injectgit'...
Branch: master
Commit: 4ceb1714
[17:53:55] Finished 'injectgit' after 33 ms
[17:53:55] Starting 'css'...
Stylus files compiled in /mnt/Big/Data/Apps/butter-desktop/src/app/themes/
[17:54:09] Finished 'css' after 14 s
[17:54:09] Starting 'nwjs'...
Using v0.18.6 (sdk)
Create cache folder in /mnt/Big/Data/Apps/butter-desktop/cache/0.18.6-sdk
Downloading: http://builds.butterproject.org/nw/v0.18.6/nwjs-sdk-v0.18.6-linux-x64.tar.gz
undefined
Unable to download NWjs.
[17:59:17] Finished 'nwjs' after 5.12 min
[17:59:17] Finished 'build' after 5.35 min
```

### Technical details
 
- OS: Ubuntu 16.10
- Version: master
- Developer tools error: N/A

**Comment by zhullGH** [comment]
Can confirm same issue happens on macOS x64.
Temporary fix for those who need to compile it for now:
Go to the gulpfile.js on the root of the project and delete the following line (don't forget the previous comma):
```
,
 downloadUrl: 'http://builds.butterproject.org/nw/'
```

**Comment by vankasteelj** [comment]
you can do that, but you wont have any other codecs than H264 (.mp4, some .mkv) in the player

**Comment by xaiki** [comment]
an update on this, the VM failed down and i can't get any news form the provider, opened tickets, called them out on twitter .=..

**Comment by xaiki** [comment]
got a new VM, syncing files now.

**Comment by xaiki** [comment]
ok,migrated DNS should be fixed, reopen if not.

**Comment by zamuro** [comment]
Changing the URL on line 124 (i.e.: the downloadUrl variable) to https://dl.nwjs.io should do the trick

**Comment by xaiki** [comment]
Our builds of nwjs have extra codecs.

**Comment by zamuro** [comment]
That might explain why it does not go past the initial screen. Any estimate on fixing the url? Or an alternative url to change the value accordingly.
