### ISSUE TITLE
Bug: Hot key, shortcuts only work in Latin/English key layout

### ISSUE THREAD

**Issue by skfd** [butterproject/butter-desktop#630]
### Issue Summary
Hot key, shortcuts only work in Latin/English key layout. They do not work for Cyrillic.

### Steps to Reproduce
We assume you have non-english keyboard layout setup and turned on.

1. Open any movie details.
2. Press `F`.
Expected: 'Add to bookmarks' toggled.
Actual: Nothing happens.

Should I make pull request? Fix would add [`keypress` argument](https://craig.is/killing/mice) to [app.js](https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/app.js#L272) and maybe other places.

### Technical details
* Butter Version: development - latest commit:  [67049278d7f62b5a95f1e47e55cb41a1cca13491](https://github.com/butterproject/butter-desktop/commit/67049278d7f62b5a95f1e47e55cb41a1cca13491)
* Downloaded from: github
* Connection: 10 MB
* OS: Windows 10

**Comment by vankasteelj** [comment]
We always welcome PRs, but why would keypress fix anything?

**Comment by skfd** [comment]
I found it in this [Moustrap issue](https://github.com/ccampbell/mousetrap/issues/2), it talks exactly about the issue. Ok, will try to work on PR.

**Comment by Leoxur** [comment]
This is happening also to me, but never try to reproduce local video by drag&dropping in the player. I have this issue, sometimes, when streaming content from popcorn's library.
Partial solution is to close and re-open popcorn until the shortcut will work again. This is important because of the "G" & "H" to sync subs

**Comment by skfd** [comment]
Fixed in current version
