### ISSUE TITLE
Error to install popcorn time 3.10 version for Windowns 10

### ISSUE THREAD

**Issue by amandavs1** [butterproject/butter-desktop#646]
### Description

I download porpcorntime version 3.10 to install and its crashed, it says an error happened and windows 10 will try to solve the problem. I'm not able to install it, how should I procedure? I tryed to restart the computer and install again, but it also did not worked. Thanks.

**Comment by vankasteelj** [comment]
You should ask to popcorn time, they do use butter, but a modified version.
