### ISSUE TITLE
Watch it Later

### ISSUE THREAD

**Issue by facundo91** [butterproject/butter-desktop#650]
### Description

Download something to watch it later.

### Steps to Reproduce 

**Expected behavior:**

I would like to choose a movie/episode/entire season to watch it later. This is specially useful for the ones that doesn't have a good healthy.

**Actual behavior:**
Actually, when I want to watch something with bad healthy, it's a horrible experience.
If I browse half an hour to find the right thing to watch, but suddenly I find out that It'll be impossible to watch it 'right now', then, It's a very sad experience.
So how can I watch it later?
If in the above example I could mark it to be download and watch it later, that would be a happy user experience.

**Comment by williamandre** [comment]
Moreover, that would allow you to seed the files while you have them, improving the quality for others (and then for you)

**Comment by jdvivar** [comment]
If you want to download something to watch later, just click on the magnet link. It will be opened and downloaded via your regular torrent app and you can watch it later.
