### ISSUE TITLE
Bug: Same movie

### ISSUE THREAD

**Issue by Benadeto** [butterproject/butter-desktop#661]
### Issue Summary
Same movie showing on Spider-man 3 and Spider-man.
### Steps to Reproduce

1. This is the first step

This is a bug because... i guess you placed same movie by accident. Maybe.

### Technical details
So i recently started watching all Spider-man movies and noticed that when i start Spider-man 3 or Spider-man it starts the same movie Spider-man 3 like there is no first Spider-man movie from 2002.
![v1](https://user-images.githubusercontent.com/30220825/28252791-e9e07194-6a9a-11e7-9d9a-0143114cac9e.gif)
![v2](https://user-images.githubusercontent.com/30220825/28252821-5e047110-6a9b-11e7-8268-e1be0aedf4ec.gif)

* Butter Version: (stable/master) - latest commit:  INSERT COMMIT REF
* Downloaded from: 
* Connection:
* OS:

**Comment by xaiki** [comment]
it looks like this is a bug in a specific butter provider or butter fork
you should probably open your bug in @team-pct
