### ISSUE TITLE
Start searching as soon as user types (not after clicking search button)

### ISSUE THREAD

**Issue by EmmanuelMess** [butterproject/butter-desktop#665]
### Description

When you start typing (supposing everything has loaded correctly) start searching. No need to press the "search" button.

### Steps to Reproduce

1. Open Popcorn Time
2. Wait until loaded
3. Start typing to search

**Comment by vankasteelj** [comment]
this spams the servers, we're working mostly with open-source and free projects.

**Comment by EmmanuelMess** [comment]
Wouldn't it have the same usage as normal search? Are you saying users will search more?

**Comment by EmmanuelMess** [comment]
My idea is to press enter to start search in database; when you start typing simply write the text in the search box.

**Comment by btzr-io** [comment]
Yeah I know what you mean,  just needs an event to listen for typing,
but I think this would cause issues with the app shortcuts ?

@EmmanuelMess Here is the current redesign, as you can see search isn't hide anymore,
 you just need to focus the input to start typing ( not really close to what you are asking,
but at least it's something :stuck_out_tongue:  )

![component-test](https://user-images.githubusercontent.com/14793624/30305120-5be0bd20-972e-11e7-93ea-c1ee3ffc14d7.jpg)

**Comment by EmmanuelMess** [comment]
@btzr-io That's for desktop? (it seems a bit thin). Also, are there shortcuts that don't start with non-writeable characters (a-z 0-9)?

**Comment by vankasteelj** [comment]
ah, I understand now. But you'll prevent keyboard shortcuts

**Comment by vankasteelj** [comment]
I'd rather have a ctrl+f then type then enter. Otherwise no keyboard shortcuts :(

**Comment by EmmanuelMess** [comment]
ctrl+f seems like a good middle ground.

**Comment by EmmanuelMess** [comment]
It seems that "ctrl+f" has already been implemented.
