### ISSUE TITLE
gulp build fails - butterproject.org website not available

### ISSUE THREAD

**Issue by joelBrun** [butterproject/butter-desktop#676]
I tried to make the installation on windows.
the 'gulp build' steps fails. 
the https://builds.butterproject.org/nw/v0.18.6/nwjs-sdk-v0.18.6-win-ia32.zip doesn't exist.

### Steps to Reproduce
gulp build

returns : 
`[18:36:03] Using gulpfile ~\Documents\butter-desktop-master\gulpfile.js
[18:36:03] Starting 'build'...
[18:36:03] Starting 'injectgit'...

Injectgit task failed
[18:36:03] Finished 'injectgit' after 134 ms
[18:36:03] Starting 'css'...
Stylus files compiled in C:\Users\jo\Documents\butter-desktop-master\src\app\themes\
[18:36:14] Finished 'css' after 11 s
[18:36:14] Starting 'nwjs'...
Using v0.18.6 (sdk)
Create cache folder in C:\Users\jo\Documents\butter-desktop-master\cache\0.18.6-sdk
Downloading: https://builds.butterproject.org/nw/v0.18.6/nwjs-sdk-v0.18.6-win-ia32.zip
undefined
Unable to download NWjs.
[18:41:23] Finished 'nwjs' after 5.15 min
[18:41:23] Finished 'build' after 5.33 min`

**Comment by joelBrun** [comment]
correction :  I think the build fails because butterproject.org is no more available.

**Comment by vankasteelj** [comment]
indeed. I'll look into it, thanks

**Comment by martijnsmitt** [comment]
Just remove the following line and you will be OK for now.
`,
    downloadUrl: 'http://builds.butterproject.org/nw/'`
This line is in the gulpfile.js and if you remove it, it will automatically download the missing file from another source.

**Comment by vankasteelj** [comment]
yes but without the custom codecs sadly, so there will be no hevc, no xvid, no ac3 and such. You should use an external player like VLC (in the settings)

**Comment by xaiki** [comment]
this should have been fixed, we just renewed the domain.
