### ISSUE TITLE
Bug: Mirrored Video on Latest version

### ISSUE THREAD

**Issue by Kurineko** [butterproject/butter-desktop#682]
The video is mirrored

Open any video in any quality

This is a bug because I can't fricking watch my movies 

* Butter Version: 6.0.9 - latest commit:  INSERT COMMIT REF?
* Downloaded from https://www.popcorn-time.to/
![miror bug](https://user-images.githubusercontent.com/36141696/35784299-932756ac-09db-11e8-90ef-550f145e6e3a.gif)
* Connection: Wi-fi 10mbps
* OS: Windows 10
(love the program, good job guys, a bug has appeared, lets squash it)
ps. this bug was reported on December in the forum

**Comment by WildYorkies** [comment]
@Kurineko Hey, you should download Popcorn Time from the website explained here https://www.reddit.com/r/PopCornTime/comments/4bbxw4/popcorn_time_faq/

>If you downloaded Popcorn Time from somewhere else, it may possibly contain a virus someone else added.

Also, your bug doesn't have enough information to replicate on other machines. I've not seen the bug so I need more exact replication steps.

**Comment by Kurineko** [comment]
yes, thank you, i got responded the same way over at Reddit, i have downloaded the real version
