### ISSUE TITLE
Update to Mn v3

### ISSUE THREAD

**Issue by paulfalgout** [butterproject/butter-desktop#689]
I'm not exactly sure the status of this project or the fork I PR'd to, but I was asked to look into updating a fork to Mn v3.  It looks fairly similar to the source, in case any one is interested.  The changes don't really utilize a v3 like architecture, but the new lib is implemented.

https://github.com/popcorn-official/popcorn-desktop/pull/721

**Comment by xaiki** [comment]
hey ! thanks a lot for your work ! i had a look at your pt code and will be integrating this into butter soon !

**Comment by xaiki** [comment]
@btzr want to look into that too ?

**Comment by btzr-io** [comment]
@xaiki  I'm not familiar with marionette or backbone, 
I'm still waiting for a full `react` / `redux` implementation
