### ISSUE TITLE
unable to run yarn build & start

### ISSUE THREAD

**Issue by XERO75** [butterproject/butter-desktop#717]
after I run yarn build failed, I try gulp build it gives me following error

`➜  butter-desktop git:(master) ✗ gulp build
[14:48:11] Using gulpfile ~/Desktop/butter-desktop/gulpfile.js
[14:48:11] Starting 'build'...
[14:48:11] Starting 'injectgit'...
Branch: master
Commit: 89e89bb8
[14:48:11] Finished 'injectgit' after 60 ms
[14:48:11] Starting 'css'...
Stylus files compiled in /Users/charlot/Desktop/butter-desktop/src/app/themes/
[14:48:13] Finished 'css' after 2.79 s
[14:48:13] Starting 'nwjs'...
{ Error: Command failed: npm ls --production=true --parseable=true
npm ERR! invalid: butter-provider-archive@0.7.0 /Users/charlot/Desktop/butter-desktop/node_modules/butter-provider-archive
npm ERR! invalid: butter-provider@0.11.0 /Users/charlot/Desktop/butter-desktop/node_modules/butter-provider-archive/node_modules/butter-provider
npm ERR! extraneous: sha.js@2.4.11 /Users/charlot/Desktop/butter-desktop/node_modules/sha.js
npm ERR! extraneous: axios@0.18.0 /Users/charlot/Desktop/butter-desktop/node_modules/axios
npm ERR! extraneous: debug@3.2.6 /Users/charlot/Desktop/butter-desktop/node_modules/butter-provider-archive/node_modules/debug
npm ERR! invalid: butter-provider-ccc@0.5.0 /Users/charlot/Desktop/butter-desktop/node_modules/butter-provider-ccc
npm ERR! invalid: butter-provider@0.11.0 /Users/charlot/Desktop/butter-desktop/node_modules/butter-provider-ccc/node_modules/butter-provider
npm ERR! extraneous: sha.js@2.4.11 /Users/charlot/Desktop/butter-desktop/node_modules/sha.js
npm ERR! extraneous: axios@0.18.0 /Users/charlot/Desktop/butter-desktop/node_modules/axios
npm ERR! extraneous: debug@3.2.6 /Users/charlot/Desktop/butter-desktop/node_modules/butter-provider-ccc/node_modules/debug
npm ERR! invalid: butter-provider-vodo@0.3.1 /Users/charlot/Desktop/butter-desktop/node_modules/butter-provider-vodo
npm ERR! invalid: butter-provider@0.11.0 /Users/charlot/Desktop/butter-desktop/node_modules/butter-provider-vodo/node_modules/butter-provider
npm ERR! extraneous: sha.js@2.4.11 /Users/charlot/Desktop/butter-desktop/node_modules/sha.js
npm ERR! extraneous: axios@0.11.1 /Users/charlot/Desktop/butter-desktop/node_modules/butter-provider-vodo/node_modules/axios
npm ERR! extraneous: debug@3.2.6 /Users/charlot/Desktop/butter-desktop/node_modules/butter-provider-vodo/node_modules/debug
npm ERR! extraneous: defer-request@0.0.2 /Users/charlot/Desktop/butter-desktop/node_modules/butter-provider-vodo/node_modules/defer-request
npm ERR! extraneous: nedb@1.8.0 /Users/charlot/Desktop/butter-desktop/node_modules/butter-provider-vodo/node_modules/nedb
npm ERR! invalid: butter-provider-youtube@0.4.0 /Users/charlot/Desktop/butter-desktop/node_modules/butter-provider-youtube
npm ERR! invalid: butter-provider@0.11.0 /Users/charlot/Desktop/butter-desktop/node_modules/butter-provider-youtube/node_modules/butter-provider
npm ERR! extraneous: sha.js@2.4.11 /Users/charlot/Desktop/butter-desktop/node_modules/sha.js
npm ERR! extraneous: debug@3.2.6 /Users/charlot/Desktop/butter-desktop/node_modules/butter-provider-youtube/node_modules/debug
npm ERR! extraneous: dayjs@1.8.6 /Users/charlot/Desktop/butter-desktop/node_modules/dayjs
npm ERR! extraneous: picotube@0.0.5 /Users/charlot/Desktop/butter-desktop/node_modules/picotube
npm ERR! invalid: node-webkit-fdialogs@0.2.7 /Users/charlot/Desktop/butter-desktop/node_modules/node-webkit-fdialogs
npm ERR! missing: colour@latest, required by ascli@0.3.0
npm ERR! missing: optjs@latest, required by ascli@0.3.0

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm ls --production=true --parseable=true' }`

**Comment by xaiki** [comment]
this issue should be fixed in latest npm.
