### ISSUE TITLE
package.json airplay-js@0.2.15 No repository field. Error

### ISSUE THREAD

**Issue by eyanez111** [butterproject/butter-desktop#72]
Hi I am installing But I am completely new but wanted to see the project and during the installation I am getting this error:

npm WARN package.json airplay-js@0.2.15 No repository field.

Loading "bower_clean.js" tasks...ERROR
>> Error: Cannot find module 'mout'
Loading "jshint.js" tasks...ERROR
>> Error: Cannot find module 'jshint/src/cli'

could I get some help on this my first installation?

**Comment by paulhobbel** [comment]
Please use `npm update`

**Comment by eyanez111** [comment]
I am still getting this error:
npm WARN package.json airplay-js@0.2.15 No repository field.
npm http GET https://registry.npmjs.org/node-webkit-fdialogs
npm http 304 https://registry.npmjs.org/node-webkit-fdialogs
npm WARN cannot run in wd Butter@0.3.8-5 node_modules/.bin/bower install --config.interactive=false && grunt setup (wd=/home/paco/Downloads/butter-master/butter)
npm WARN unmet dependency /home/paco/Downloads/butter-master/butter/node_modules/bower requires mkdirp@'0.5.0' but will load
npm WARN unmet dependency /home/paco/Downloads/butter-master/butter/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.1



Loading "bower_clean.js" tasks...ERROR
>> Error: Cannot find module './util/cli'
Loading "jshint.js" tasks...ERROR
>> Error: Cannot find module 'jshint/src/cli'
Warning: Task "bower_clean" not found. Use --force to continue.

Aborted due to warnings.
Butter encountered an error and couldn't be built


Any advise?

**Comment by Kikobeats** [comment]
what version of npm do you use?

try `npm install -g npm` and later try again to fetch the dependency

**Comment by eyanez111** [comment]
Thanks a lot for the input,

installed -g npm run again to find dependencies and got:

npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.25
npm ERR! npm  v3.3.9
npm ERR! path /home/paco/Downloads/butter-master/butter/node_modules/readline2/node_modules/strip-ansi/cli.js
npm ERR! code ENOENT
npm ERR! errno 34

npm ERR! enoent ENOENT, chmod '/home/paco/Downloads/butter-master/butter/node_modules/readline2/node_modules/strip-ansi/cli.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/paco/Downloads/butter-master/butter/npm-debug.log
Local dependencies encountered an error while installing

there are no dependencies.. Any advise on what to do with this ?

Thanks for the support

**Comment by tomHaum** [comment]
I am getting a similar problem, maybe unrelated. I ran `npm update`

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "update"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone C:\Users\Tom\AppData\Roaming\npm-cache\_git-remotes\https-github-com-guerrerocarlos-node-airplay-js-git-e5fe15a1 C:\Users\Tom\AppData\Local\Temp\npm-11300-56ff5d7c\git-cache-03d1ae9ca7d5\dae2c65ee92036c51e5efaad8b120aef4156af03
npm ERR! Cloning into 'C:\Users\Tom\AppData\Local\Temp\npm-11300-56ff5d7c\git-cache-03d1ae9ca7d5\dae2c65ee92036c51e5efaad8b120aef4156af03'...
npm ERR! fatal: '/cygdrive/c/Users/Tom/AppData/Roaming/npm-cache/_git-remotes/https-github-com-guerrerocarlos-node-airplay-js-git-e5fe15a1/C:\Users\Tom\AppData\Roaming\npm-cache\_git-remotes\https-github-com-guerrerocarlos-node-airplay-js-git-e5fe15a1' does not appear to be a git repository
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

**Comment by eyanez111** [comment]
Does not seem to be related as is a problem in linux... Not sure how to proceed where. Stuck

**Comment by eyanez111** [comment]
Is any one out there with this same problem? I have looked over and have not find anyone...
