### ISSUE TITLE
Bug: avengers infinity war subtitles in french are shifted

### ISSUE THREAD

**Issue by ryu200045156** [butterproject/butter-desktop#724]
### Steps to Reproduce

1. This is the first step

avengers infinity war subtitles in french are shifted from audio in english

### Technical details

* Butter Version: (stable/master) - latest commit:  INSERT COMMIT REF
* Downloaded from: PC
* Connection:
* OS: windows 10 pro

**Comment by xaiki** [comment]
this is not popcorn.
